DROP TABLE STORE;
DROP TABLE PRODUCT;
DROP TABLE PAYMENT;
DROP TABLE TB_CATEGORY;
DROP TABLE NOTICE;
DROP TABLE QNA;
DROP TABLE MEMBER;
DROP TABLE TB_CODE;
DROP TABLE TB_CHA_FILE;
DROP TABLE MESSAGE;
DROP TABLE TB_CH_DETAIL_INFO;
DROP TABLE LIKES;
DROP TABLE REPORT;
DROP TABLE FAQ;
DROP TABLE STORE_ATTA;
DROP TABLE PRODUCT_ATTA;
DROP TABLE DY_BOARD;
DROP TABLE CHAT;
DROP TABLE GRADE;
DROP TABLE DY_REPLY;
DROP TABLE TB_CH_CON_REPLY;
DROP TABLE REVIEW;
DROP TABLE REVIEW_REPLY;
DROP TABLE ORDERS;
DROP TABLE POINT;
DROP TABLE CART;
DROP TABLE TB_GRP_CODE;
DROP TABLE TB_CATEGORY_TEMPLATE;
DROP TABLE TB_CH_CONFIRM;
DROP TABLE TB_CHALLENGE;

DROP SEQUENCE SEQ_TB_CHALLENGE;
DROP SEQUENCE SEQ_STORE;
DROP SEQUENCE SEQ_PRODUCT;
DROP SEQUENCE SEQ_PAYMENT;
DROP SEQUENCE SEQ_TB_CATEGORY;
DROP SEQUENCE SEQ_NOTICE;
DROP SEQUENCE SEQ_TB_CATEGORY_TEMPLATE;
DROP SEQUENCE SEQ_QNA;
DROP SEQUENCE SEQ_MEMBER;
DROP SEQUENCE SEQ_TB_GRP_CODE;
DROP SEQUENCE SEQ_TB_CODE;
DROP SEQUENCE SEQ_TB_CHA_FILE;
DROP SEQUENCE SEQ_MESSAGE;
DROP SEQUENCE SEQ_TB_CH_CONFIRM;
DROP SEQUENCE SEQ_TB_CH_DETAIL_INFO;
DROP SEQUENCE SEQ_LIKE;
DROP SEQUENCE SEQ_REPORT;
DROP SEQUENCE SEQ_FAQ;
DROP SEQUENCE SEQ_STORE_ATTA;
DROP SEQUENCE SEQ_PRODUCT_ATTA;
DROP SEQUENCE SEQ_DY_BOARD;
DROP SEQUENCE SEQ_CHAT;
DROP SEQUENCE SEQ_GRADE;
DROP SEQUENCE SEQ_DY_REPLY;
DROP SEQUENCE SEQ_TB_CH_CON_REPLY;
DROP SEQUENCE SEQ_REVIEW;
DROP SEQUENCE SEQ_REVIEW_REPLY;
DROP SEQUENCE SEQ_ORDER;
DROP SEQUENCE SEQ_POINT;
DROP SEQUENCE SEQ_CART;


CREATE TABLE TB_CHALLENGE
(
    CH_NO        NUMBER NOT NULL,
    CH_TITLE     VARCHAR2(100) NOT NULL,
    CH_START_DAY VARCHAR2(8) NOT NULL,
    CH_END_DAY   VARCHAR2(8) NOT NULL,
    MEMBER_ID    VARCHAR2(100) NOT NULL,
    CATEGORY_NO  NUMBER NOT NULL,
    FILE_NO      NUMBER NOT NULL,
    CODE         VARCHAR2(8) NOT NULL,
    CH_CONTENT   CLOB NOT NULL
);

CREATE SEQUENCE SEQ_TB_CHALLENGE;

CREATE TABLE STORE_REGION
(
    STORE_REGION_NO NUMBER PRIMARY KEY,
    CITY            VARCHAR2(50),
    PROVINCES       VARCHAR2(50),
    CONSTRAINT city_province_unique UNIQUE (CITY, PROVINCES)
);

CREATE TABLE STORE
(
    STORE_NO        NUMBER           NOT NULL,
    STORE_NAME      VARCHAR2(50) NOT NULL,
    STORE_ADDRESS   VARCHAR2(200) NOT NULL,
    STORE_PHONE     VARCHAR2(30) NULL,
    BUSINESS_HOURS  VARCHAR2(20) NULL,
    STORE_RC        NUMBER DEFAULT 0 NOT NULL,
    STORE_LAT       NUMBER NULL,
    STORE_LON       NUMBER NULL,
    STORE_REGION_NO NUMBER NULL,
    STORE_INFO      VARCHAR2(500),
    STATUS       CHAR(1) DEFAULT 'Y'     NOT NULL,
    FOREIGN KEY (STORE_REGION_NO) REFERENCES STORE_REGION (STORE_REGION_NO)
);

CREATE SEQUENCE SEQ_STORE;

CREATE TABLE PRODUCT
(
    PRODUCT_NO   NUMBER                  NOT NULL,
    PRODUCT_NAME VARCHAR2(100) NOT NULL,
    CATEGORY     VARCHAR2(20) NOT NULL,
    PRICE        NUMBER                  NOT NULL,
    DISCOUNT     NUMBER  DEFAULT 0       NOT NULL,
    STOCK        NUMBER  DEFAULT 0       NOT NULL,
    CREATE_DATE  DATE    DEFAULT SYSDATE NOT NULL,
    STATUS       CHAR(1) DEFAULT 'Y'     NOT NULL
);

CREATE SEQUENCE SEQ_PRODUCT;

CREATE TABLE PAYMENT
(
    PAYMENT_NO             NUMBER NOT NULL,
    MEMBER_ID              VARCHAR2(100) NOT NULL,
    PAYMENT_DATE           DATE DEFAULT SYSDATE NULL,
    PAYMENT_TYPE           VARCHAR2(20) NOT NULL,
    STATUS                 VARCHAR2(1) DEFAULT 'Y' NOT NULL,
    PAYMENT_TOTAL          NUMBER NOT NULL,
    RECEIVE_NAME           VARCHAR2(20) NOT NULL,
    RECEIVE_PHONE          VARCHAR2(11) NOT NULL,
    POST_CODE              VARCHAR2(5) NOT NULL,
    ADDRESS1               VARCHAR2(100) NOT NULL,
    ADDRESS2               VARCHAR2(100) NOT NULL,
    DELIVERY_COMMENT        VARCHAR2(100),
    PAYMENT_TOKEN          VARCHAR2(40) NOT NULL
);

CREATE SEQUENCE SEQ_PAYMENT;

CREATE TABLE TB_CATEGORY
(
    CATEGORY_NO   NUMBER NOT NULL,
    CATEGORY_NAME VARCHAR2(100) NOT NULL,
    STATUS        VARCHAR2(1) DEFAULT 'Y' NOT NULL
);

CREATE SEQUENCE SEQ_TB_CATEGORY;

CREATE TABLE NOTICE
(
    NOTICE_NO       NUMBER                  NOT NULL,
    NOTICE_TITLE    VARCHAR2(100) NOT NULL,
    NOTICE_CONTENT  VARCHAR2(500) NOT NULL,
    CREATED_AT      DATE    DEFAULT SYSDATE NOT NULL,
    STATUS          CHAR(1) DEFAULT 'Y'     NOT NULL,
    NOTICE_CATEGORY VARCHAR2(15) NOT NULL,
    NOTICE_VIEW     NUMBER  DEFAULT 0       NOT NULL
);

CREATE SEQUENCE SEQ_NOTICE;

CREATE TABLE TB_CATEGORY_TEMPLATE
(
    CATEGORY_TEMPLATE_NO NUMBER NOT NULL,
    INPUT_TYPE           VARCHAR2(20) NOT NULL,
    STATUS               VARCHAR2(1) DEFAULT 'Y' NOT NULL,
    SORT_NO              NUMBER NOT NULL,
    CH_SUB_TITLE         VARCHAR2(200) NULL,
    GRP_CODE             VARCHAR2(8) NOT NULL,
    CATEGORY_NO          NUMBER NOT NULL
);

CREATE SEQUENCE SEQ_TB_CATEGORY_TEMPLATE;

CREATE TABLE QNA
(
    BOARD_NO      NUMBER               NOT NULL,
    BOARD_TITLE   VARCHAR2(100) NOT NULL,
    BOARD_CONTENT VARCHAR(2000)        NOT NULL,
    BOARD_DATE    DATE DEFAULT SYSDATE NOT NULL,
    BOARD_REPLY   VARCHAR(1000) NULL,
    MEMBER_ID     VARCHAR2(100) NOT NULL
);

CREATE SEQUENCE SEQ_QNA;

CREATE TABLE MEMBER
(
    MEMBER_ID    VARCHAR2(100) NOT NULL,
    MEMBER_PWD   VARCHAR2(100) NOT NULL,
    MEMBER_NAME  VARCHAR2(20) NOT NULL,
    EMAIL        VARCHAR2(30) NOT NULL,
    BIRTH_DATE   DATE NULL,
    PHONE        CHAR(11)                NOT NULL,
    GENDER       CHAR(1) NULL,
    CREATED_DATE DATE    DEFAULT SYSDATE NOT NULL,
    STATUS       CHAR(1) DEFAULT 'Y'     NOT NULL,
    TOTAL_PAY    NUMBER  DEFAULT 0       NOT NULL,
    ADDRESS1     VARCHAR2(255) NULL,
    ADDRESS2     VARCHAR2(255) NULL,
    CHANGE_NAME  VARCHAR2(255) NULL,
    GRADE_NAME   VARCHAR2(15) DEFAULT 'RED' NOT NULL,
    POST_CODE    VARCHAR2(5),
    MAIL_AUTH    NUMBER DEFAULT 0,
    MAIL_KEY     VARCHAR2(50),
    TOTAL_POINT  NUMBER DEFAULT 0
);

CREATE SEQUENCE SEQ_MEMBER;

CREATE TABLE TB_GRP_CODE
(
    GRP_CODE      VARCHAR2(8) NOT NULL,
    GRP_CODE_NAME VARCHAR2(100) NOT NULL,
    STATUS        VARCHAR2(1) DEFAULT 'Y' NOT NULL
);

CREATE SEQUENCE SEQ_TB_GRP_CODE;

CREATE TABLE TB_CODE
(
    CODE      VARCHAR2(8) NOT NULL,
    GRP_CODE  VARCHAR2(8) NOT NULL,
    CODE_NAME VARCHAR2(100) NOT NULL,
    STATUS    VARCHAR2(1) DEFAULT 'Y' NOT NULL,
    SORT_NO   NUMBER NOT NULL
);

CREATE SEQUENCE SEQ_TB_CODE;

CREATE TABLE TB_CHA_FILE
(
    FILE_NO   NUMBER NOT NULL,
    FILE_NAME VARCHAR2(100) NOT NULL,
    FILE_PATH VARCHAR2(300) NOT NULL
);

CREATE SEQUENCE SEQ_TB_CHA_FILE;

CREATE TABLE MESSAGE
(
    MESSAGE_NO      NUMBER               NOT NULL,
    SEND_TIME       DATE DEFAULT SYSDATE NOT NULL,
    MESSAGE_CONTENT VARCHAR(1000)        NOT NULL,
    CH_NO           NUMBER               NOT NULL,
    CATEGORY_NO     NUMBER               NOT NULL
);

CREATE SEQUENCE SEQ_MESSAGE;

CREATE TABLE TB_CH_CONFIRM
(
    CH_CON_NO          NUMBER               NOT NULL,
    CH_NO              NUMBER               NOT NULL,
    CH_CON_TITLE       VARCHAR2(200) NOT NULL,
    CH_CON_CONTENT     VARCHAR2(4000) NOT NULL,
    MEMBER_ID          VARCHAR2(100) NOT NULL,
    STATUS             VARCHAR2(1) DEFAULT 'Y' NOT NULL,
    CH_CON_CREATE_DATE DATE DEFAULT SYSDATE NOT NULL
);

CREATE SEQUENCE SEQ_TB_CH_CONFIRM;

CREATE TABLE TB_CH_DETAIL_INFO
(
    CH_DETAIL_INFO_NO    NUMBER NOT NULL,
    CH_NO                NUMBER NOT NULL,
    CH_CON_NO            NUMBER NOT NULL,
    CATEGORY_TEMPLATE_NO NUMBER NOT NULL,
    CH_DETAIL_INFO_DATA  VARCHAR2(4000) NOT NULL,
    STATUS               VARCHAR2(1) DEFAULT 'Y' NOT NULL,
    CODE                 VARCHAR2(8) NOT NULL,
    FILE_NO              NUMBER NOT NULL
);

CREATE SEQUENCE SEQ_TB_CH_DETAIL_INFO;

CREATE TABLE LIKES
(
    MEMBER_ID  VARCHAR2(100) NOT NULL,
    PRODUCT_NO NUMBER NOT NULL
);

CREATE SEQUENCE SEQ_LIKE;

CREATE TABLE REPORT
(
    REPORT_NO      NUMBER NOT NULL,
    REPORT_CONTENT VARCHAR2(3000) NOT NULL,
    CH_CON_NO      NUMBER NOT NULL,
    CH_NO          NUMBER NOT NULL,
    DY_BOARD_NO    NUMBER NOT NULL,
    MEMBER_ID      VARCHAR2(100) NOT NULL
);

CREATE SEQUENCE SEQ_REPORT;

CREATE TABLE FAQ
(
    FAQ_NO       NUMBER        NOT NULL,
    FAQ_QUESTION VARCHAR2(100) NOT NULL,
    FAQ_ANSWER   VARCHAR(2000) NOT NULL,
    FAQ_CATEGORY VARCHAR(50)   NOT NULL
);

CREATE SEQUENCE SEQ_FAQ;

CREATE TABLE STORE_ATTA
(
    FILE_NO   NUMBER NOT NULL,
    FILE_NAME VARCHAR2(100) NOT NULL,
    FILE_PATH VARCHAR2(300) NOT NULL,
    STORE_NO  NUMBER NOT NULL
);

CREATE SEQUENCE SEQ_STORE_ATTA;

CREATE TABLE PRODUCT_ATTA
(
    ATTACHMENT_NO NUMBER NOT NULL,
    CHANGER_NAME  VARCHAR2(255) NOT NULL,
    FILE_LEVEL    NUMBER NOT NULL,
    PRODUCT_NO    NUMBER NOT NULL
);

CREATE SEQUENCE SEQ_PRODUCT_ATTA;

CREATE TABLE DY_BOARD
(
    DY_BOARD_NO      NUMBER NOT NULL,
    DY_BOARD_TITLE   VARCHAR2(100) NOT NULL,
    DY_BOARD_CONTENT VARCHAR2(4000) NOT NULL,
    DY_CREATE_DATE   DATE   DEFAULT SYSDATE NULL,
    DY_STATUS        VARCHAR2(1) DEFAULT 'Y' NULL,
    DY_COUNT         NUMBER DEFAULT 0 NULL,
    ORIGIN_NAME      VARCHAR2(100) NOT NULL,
    CHANGE_NAME      VARCHAR2(100) NOT NULL,
    MEMBER_ID        VARCHAR2(100) NOT NULL
);

CREATE SEQUENCE SEQ_DY_BOARD;

CREATE TABLE CHAT
(
    CH_NO       NUMBER NOT NULL,
    CREATE_DATE DATE NULL,
    MEMBER_ID   VARCHAR2(100) NOT NULL
);

CREATE SEQUENCE SEQ_CHAT;

CREATE TABLE GRADE
(
    GRADE_NAME  VARCHAR2(15) DEFAULT 'RED' NOT NULL,
    PAYMENT_MIN NUMBER NOT NULL,
    PAYMENT_MAX NUMBER NOT NULL
);

CREATE SEQUENCE SEQ_GRADE;

CREATE TABLE DY_REPLY
(
    DY_REPLY_NO      NUMBER               NOT NULL,
    DY_BOARD_NO      NUMBER               NOT NULL,
    DY_REPLY_CONTENT VARCHAR2(400) NOT NULL,
    DY_CREATE_DATE   DATE DEFAULT SYSDATE NOT NULL,
    DY_STATUS        VARCHAR2(1) DEFAULT 'Y' NULL,
    MEMBER_ID        VARCHAR2(100) NOT NULL
);

CREATE SEQUENCE SEQ_DY_REPLY;

CREATE TABLE TB_CH_CON_REPLY
(
    RE_NO          NUMBER               NOT NULL,
    CH_CON_NO      NUMBER               NOT NULL,
    CH_NO          NUMBER               NOT NULL,
    RE_CONTENT     VARCHAR2(2000) NOT NULL,
    RE_CREATE_DATE DATE DEFAULT SYSDATE NOT NULL,
    STATUS         VARCHAR2(1) DEFAULT 'Y' NOT NULL,
    MEMBER_ID      VARCHAR2(100) NOT NULL
);

CREATE SEQUENCE SEQ_TB_CH_CON_REPLY;

CREATE TABLE REVIEW
(
    REVIEW_NO      NUMBER               NOT NULL,
    REVIEW_CONTENT VARCHAR2(1000) NOT NULL,
    CREATE_DATE    DATE DEFAULT SYSDATE NOT NULL,
    RATING         NUMBER               NOT NULL,
    CHANGE_NAME    VARCHAR2(255) NULL,
    PRODUCT_NO     NUMBER               NOT NULL,
    MEMBER_ID      VARCHAR2(100) NOT NULL
);

CREATE SEQUENCE SEQ_REVIEW;

CREATE TABLE REVIEW_REPLY
(
    RV_REPLY_NO   NUMBER                  NOT NULL,
    REPLY_CONTENT VARCHAR2(1000) NOT NULL,
    CREATED_DATE  DATE    DEFAULT SYSDATE NOT NULL,
    STATUS        CHAR(1) DEFAULT 'Y'     NOT NULL,
    REVIEW_NO     NUMBER                  NOT NULL,
    MEMBER_ID     VARCHAR2(100) NOT NULL
);

CREATE SEQUENCE SEQ_REVIEW_REPLY;

CREATE TABLE ORDERS
(
    ORDER_NO       NUMBER           NOT NULL,
    PRODUCT_AMOUNT NUMBER DEFAULT 1 NOT NULL,
    PAYMENT_NO     NUMBER           NOT NULL,
    PRODUCT_NO     NUMBER           NOT NULL
);

CREATE SEQUENCE SEQ_ORDER;

CREATE TABLE POINT
(
    POINT_NO      NUMBER               NOT NULL,
    POINT_CONTENT VARCHAR2(300) NOT NULL,
    POINT_NUM     NUMBER               NOT NULL,
    STATUS        CHAR(3)              NOT NULL,
    POINT_DATE    DATE DEFAULT SYSDATE NOT NULL,
    MEMBER_ID     VARCHAR2(100) NOT NULL
);

CREATE SEQUENCE SEQ_POINT;

CREATE TABLE CART
(
    CART_NO    NUMBER NOT NULL,
    AMOUNT     NUMBER NOT NULL,
    PRICE      NUMBER NOT NULL,
    PRODUCT_NO NUMBER NOT NULL,
    MEMBER_ID  VARCHAR2(100) NOT NULL
);

CREATE SEQUENCE SEQ_CART;



ALTER TABLE TB_CHALLENGE
    ADD CONSTRAINT PK_TB_CHALLENGE PRIMARY KEY (CH_NO);

ALTER TABLE STORE
    ADD CONSTRAINT PK_STORE PRIMARY KEY (STORE_NO);

ALTER TABLE PRODUCT
    ADD CONSTRAINT PK_PRODUCT PRIMARY KEY (PRODUCT_NO);

ALTER TABLE PAYMENT
    ADD CONSTRAINT PK_PAYMENT PRIMARY KEY (PAYMENT_NO);

ALTER TABLE TB_CATEGORY
    ADD CONSTRAINT PK_TB_CATEGORY PRIMARY KEY (CATEGORY_NO);

ALTER TABLE NOTICE
    ADD CONSTRAINT PK_NOTICE PRIMARY KEY (NOTICE_NO);

ALTER TABLE TB_CATEGORY_TEMPLATE
    ADD CONSTRAINT PK_TB_CATEGORY_TEMPLATE PRIMARY KEY (CATEGORY_TEMPLATE_NO);

ALTER TABLE QNA
    ADD CONSTRAINT PK_QNA PRIMARY KEY (BOARD_NO);

ALTER TABLE MEMBER
    ADD CONSTRAINT PK_MEMBER PRIMARY KEY (MEMBER_ID);

ALTER TABLE TB_GRP_CODE
    ADD CONSTRAINT PK_TB_GRP_CODE PRIMARY KEY (GRP_CODE);

ALTER TABLE TB_CODE
    ADD CONSTRAINT PK_TB_CODE PRIMARY KEY (CODE, GRP_CODE);

ALTER TABLE TB_CHA_FILE
    ADD CONSTRAINT PK_TB_CHA_FILE PRIMARY KEY (FILE_NO);

ALTER TABLE MESSAGE
    ADD CONSTRAINT PK_MESSAGE PRIMARY KEY (MESSAGE_NO);

ALTER TABLE TB_CH_CONFIRM
    ADD CONSTRAINT PK_TB_CH_CONFIRM PRIMARY KEY (CH_CON_NO, CH_NO);

ALTER TABLE TB_CH_DETAIL_INFO
    ADD CONSTRAINT PK_TB_CH_DETAIL_INFO PRIMARY KEY (CH_DETAIL_INFO_NO, CH_CON_NO, CH_NO, CATEGORY_TEMPLATE_NO);

ALTER TABLE REPORT
    ADD CONSTRAINT PK_REPORT PRIMARY KEY (REPORT_NO);

ALTER TABLE FAQ
    ADD CONSTRAINT PK_FAQ PRIMARY KEY (FAQ_NO);

ALTER TABLE STORE_ATTA
    ADD CONSTRAINT PK_STORE_ATTA PRIMARY KEY (FILE_NO);

ALTER TABLE PRODUCT_ATTA
    ADD CONSTRAINT PK_PRODUCT_ATTA PRIMARY KEY (ATTACHMENT_NO);

ALTER TABLE DY_BOARD
    ADD CONSTRAINT PK_DY_BOARD PRIMARY KEY (DY_BOARD_NO);

ALTER TABLE CHAT
    ADD CONSTRAINT PK_CHAT PRIMARY KEY (CH_NO);

ALTER TABLE GRADE
    ADD CONSTRAINT PK_GRADE PRIMARY KEY (GRADE_NAME);

ALTER TABLE DY_REPLY
    ADD CONSTRAINT PK_DY_REPLY PRIMARY KEY (DY_REPLY_NO);

ALTER TABLE TB_CH_CON_REPLY
    ADD CONSTRAINT PK_TB_CH_CON_REPLY PRIMARY KEY (RE_NO, CH_CON_NO, CH_NO);

ALTER TABLE REVIEW
    ADD CONSTRAINT PK_REVIEW PRIMARY KEY (REVIEW_NO);

ALTER TABLE REVIEW_REPLY
    ADD CONSTRAINT PK_REVIEW_REPLY PRIMARY KEY (RV_REPLY_NO);

ALTER TABLE ORDERS
    ADD CONSTRAINT PK_ORDER PRIMARY KEY (ORDER_NO);

ALTER TABLE POINT
    ADD CONSTRAINT PK_POINT PRIMARY KEY (POINT_NO);

ALTER TABLE CART
    ADD CONSTRAINT PK_CART PRIMARY KEY (CART_NO);



ALTER TABLE TB_CODE
    ADD CONSTRAINT FK_TB_GRP_CODE FOREIGN KEY (GRP_CODE)
        REFERENCES TB_GRP_CODE (GRP_CODE);

ALTER TABLE TB_CH_CONFIRM
    ADD CONSTRAINT FK_TB_CHALLENGE FOREIGN KEY (CH_NO)
        REFERENCES TB_CHALLENGE (CH_NO);

ALTER TABLE TB_CH_DETAIL_INFO
    ADD CONSTRAINT FK_TB_CHALLENGE2 FOREIGN KEY (CH_NO)
        REFERENCES TB_CHALLENGE (CH_NO);

ALTER TABLE TB_CH_DETAIL_INFO
    ADD CONSTRAINT FK_TB_CATEGORY_TEMPLATE FOREIGN KEY (CATEGORY_TEMPLATE_NO)
        REFERENCES TB_CATEGORY_TEMPLATE (CATEGORY_TEMPLATE_NO);

ALTER TABLE CHAT
    ADD CONSTRAINT FK_TB_CHALLENGE3 FOREIGN KEY (CH_NO)
        REFERENCES TB_CHALLENGE (CH_NO);

ALTER TABLE TB_CH_CON_REPLY
    ADD CONSTRAINT FK_TB_CH_CONFIRM1 FOREIGN KEY (CH_CON_NO, CH_NO)
        REFERENCES TB_CH_CONFIRM (CH_CON_NO, CH_NO);


------------------- [ 챌린�??�???�� ?��?�� ] ------------------- 
-- < ?��?��조건 �??경사?�� >

ALTER TABLE TB_CH_DETAIL_INFO
DROP
CONSTRAINT SYS_C0010294;


ALTER TABLE TB_CH_DETAIL_INFO
DROP
CONSTRAINT SYS_C0010295;


---------------------------------------------------------------------------------------
--  < ?��???�� �??경사?�� >
-- 1. TB_CATEGORY ?��???��
DROP SEQUENCE SEQ_CATE_NO;

CREATE SEQUENCE SEQ_CATE_NO
    START WITH 10000000;

SELECT SEQ_CATE_NO.NEXTVAL
FROM DUAL;


-- 2. TB_CATEGORY_TEMPLATE ?��???�� 
DROP SEQUENCE SEQ_TB_CATEGORY_TEMPLATE;

CREATE SEQUENCE SEQ_TB_CATEGORY_TEMPLATE
    START WITH 10000000;

SELECT SEQ_TB_CATEGORY_TEMPLATE.NEXTVAL
FROM DUAL;


-----------------------------------------------------------------------------------
-- < 컬럼 �??경사?�� >

ALTER TABLE TB_CHALLENGE DROP COLUMN CODE;

ALTER TABLE TB_CATEGORY_TEMPLATE DROP COLUMN GRP_CODE;

------------------------------------------------------------------------------------
-- < 코멘?�� >
-- 1. TB_CATEGORY
COMMENT
ON COLUMN TB_CATEGORY.CATEGORY_NO IS '카테고리 ?��?��번호';
COMMENT
ON COLUMN TB_CATEGORY.CATEGORY_NAME IS '카테고리�??';
COMMENT
ON COLUMN TB_CATEGORY.STATUS IS '?��?��?���??';

-- 2. TB_CATEGORY_TEMPLATE
COMMENT
ON COLUMN TB_CATEGORY_TEMPLATE.CATEGORY_TEMPLATE_NO IS '?��?���?? ?��?��번호';
COMMENT
ON COLUMN TB_CATEGORY_TEMPLATE.INPUT_TYPE IS '?��?��???��';
COMMENT
ON COLUMN TB_CATEGORY_TEMPLATE.STATUS IS '?��?��?���??';
COMMENT
ON COLUMN TB_CATEGORY_TEMPLATE.SORT_NO IS '?��?��?��?��';
COMMENT
ON COLUMN TB_CATEGORY_TEMPLATE.CH_SUB_TITLE IS '챌린�?? ?��?���??';
COMMENT
ON COLUMN TB_CATEGORY_TEMPLATE.CATEGORY_NO IS '카테고리 ?��?��번호';

-- 3. TB_CH_CON_REPLY
COMMENT
ON COLUMN TB_CH_CON_REPLY.RE_NO IS '?���??번호';
COMMENT
ON COLUMN TB_CH_CON_REPLY.CH_CON_NO IS '챌린�?? ?���?? ?��?��번호';
COMMENT
ON COLUMN TB_CH_CON_REPLY.CH_NO IS '챌린�?? ?��?��번호';
COMMENT
ON COLUMN TB_CH_CON_REPLY.RE_CONTENT IS '?���???��?��';
COMMENT
ON COLUMN TB_CH_CON_REPLY.RE_CREATE_DATE IS '?��?��?��';
COMMENT
ON COLUMN TB_CH_CON_REPLY.STATUS IS '?��?��?���??';
COMMENT
ON COLUMN TB_CH_CON_REPLY.MEMBER_ID IS '?��?��?��?��?��';

-- 4. TB_CH_CONFIRM
COMMENT
ON COLUMN TB_CH_CONFIRM.CH_CON_NO IS '챌린�?? ?���?? ?��?��번호';
COMMENT
ON COLUMN TB_CH_CONFIRM.CH_NO IS '챌린�?? ?��?��번호';
COMMENT
ON COLUMN TB_CH_CONFIRM.CH_CON_TITLE IS '챌린�?? ?���?? ?���??';
COMMENT
ON COLUMN TB_CH_CONFIRM.CH_CON_CONTENT IS '챌린�?? ?���?? ?��?��';
COMMENT
ON COLUMN TB_CH_CONFIRM.MEMBER_ID IS '?��?��?��?��?��';
COMMENT
ON COLUMN TB_CH_CONFIRM.STATUS IS '?��?��?���??';
COMMENT
ON COLUMN TB_CH_CONFIRM.CH_CON_CREATE_DATE IS '?��?��?��';

-- 5. TB_CH_DETAIL_INFO
COMMENT
ON COLUMN TB_CH_DETAIL_INFO.CH_DETAIL_INFO_NO IS '챌린�?? ?��?��?���?? ?��?��번호';
COMMENT
ON COLUMN TB_CH_DETAIL_INFO.CH_NO IS '챌린�?? ?��?��번호';
COMMENT
ON COLUMN TB_CH_DETAIL_INFO.CATEGORY_TEMPLATE_NO IS '?��?���?? ?��?��번호';
COMMENT
ON COLUMN TB_CH_DETAIL_INFO.CH_DETAIL_INFO_DATA IS '챌린�?? ?��?��?���?? ?��?��?��';
COMMENT
ON COLUMN TB_CH_DETAIL_INFO.STATUS IS '?��?��?���??';
COMMENT
ON COLUMN TB_CH_DETAIL_INFO.CODE IS '코드';
COMMENT
ON COLUMN TB_CH_DETAIL_INFO.FILE_NO IS '?��?�� ?��?��번호';

-- 6. TB_CHA_FILE
COMMENT
ON COLUMN TB_CHA_FILE.FILE_NO IS '?��?�� ?��?��번호';
COMMENT
ON COLUMN TB_CHA_FILE.FILE_NAME IS '?��?���??';
COMMENT
ON COLUMN TB_CHA_FILE.FILE_PATH IS '?��?��경로';

-- 7. TB_CHALLENGE
COMMENT
ON COLUMN TB_CHALLENGE.CH_NO IS '챌린�?? ?��?��번호';
COMMENT
ON COLUMN TB_CHALLENGE.CH_TITLE IS '챌린�??�??';
COMMENT
ON COLUMN TB_CHALLENGE.CH_START_DAY IS '챌린�?? ?��?��?��';
COMMENT
ON COLUMN TB_CHALLENGE.CH_END_DAY IS '챌린�?? 종료?��';
COMMENT
ON COLUMN TB_CHALLENGE.MEMBER_ID IS '?��?��?��?��?��';
COMMENT
ON COLUMN TB_CHALLENGE.CATEGORY_NO IS '카테고리 ?��?��번호';
COMMENT
ON COLUMN TB_CHALLENGE.FILE_NO IS '?��?�� ?��?��번호';

-- 8. TB_CODE
COMMENT
ON COLUMN TB_CODE.CODE IS '코드';
COMMENT
ON COLUMN TB_CODE.GRP_CODE IS '그룹코드';
COMMENT
ON COLUMN TB_CODE.CODE_NAME IS '코드�??';
COMMENT
ON COLUMN TB_CODE.STATUS IS '?��?��?���??';
COMMENT
ON COLUMN TB_CODE.SORT_NO IS '?��?��?��?��';


-- 9. TB_GRP_CODE
COMMENT
ON COLUMN TB_GRP_CODE.GRP_CODE IS '그룹코드';
COMMENT
ON COLUMN TB_GRP_CODE.GRP_CODE_NAME IS '그룹코드�??';
COMMENT
ON COLUMN TB_GRP_CODE.STATUS IS '?��?��?���??';
------------------- [ 챌린�??�???�� ?�� ] ------------------- 


-- STORE_REGION ?���??
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (1, '?��?��?��별시', '종로�??');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (2, '?��?��?��별시', '중구');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (3, '?��?��?��별시', '?��?���??');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (4, '?��?��?��별시', '?��?���??');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (5, '?��?��?��별시', '광진�??');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (6, '?��?��?��별시', '?��??문구');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (7, '?��?��?��별시', '중랑�??');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (8, '?��?��?��별시', '?��북구');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (9, '?��?��?��별시', '강북�??');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (10, '?��?��?��별시', '?��봉구');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (11, '?��?��?��별시', '?��?���??');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (12, '?��?��?��별시', '???���??');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (13, '?��?��?��별시', '?��??문구');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (14, '?��?��?��별시', '마포�??');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (15, '?��?��?��별시', '?��천구');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (16, '?��?��?��별시', '강서�??');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (17, '?��?��?��별시', '구로�??');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (18, '?��?��?��별시', '금천�??');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (19, '?��?��?��별시', '?��?��?���??');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (20, '?��?��?��별시', '?��?���??');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (21, '?��?��?��별시', '�???���??');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (22, '?��?��?��별시', '?��초구');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (23, '?��?��?��별시', '강남�??');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (24, '?��?��?��별시', '?��?���??');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (25, '?��?��?��별시', '강동�??');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (26, '�???��광역?��', '중구');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (27, '�???��광역?��', '?���??');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (28, '�???��광역?��', '?���??');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (29, '�???��광역?��', '?��?���??');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (30, '�???��광역?��', '�???��진구');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (31, '�???��광역?��', '?��?���??');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (32, '�???��광역?��', '?���??');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (33, '�???��광역?��', '북구');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (34, '�???��광역?��', '강서�??');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (35, '�???��광역?��', '?��?��??�??');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (36, '�???��광역?��', '?��?���??');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (37, '�???��광역?��', '금정�??');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (38, '�???��광역?��', '?��?���??');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (39, '�???��광역?��', '?��?���??');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (40, '�???��광역?��', '?��?���??');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (41, '�???��광역?��', '기장�??');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (42, '??구광?��?��', '중구');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (43, '??구광?��?��', '?���??');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (44, '??구광?��?��', '?���??');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (45, '??구광?��?��', '?���??');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (46, '??구광?��?��', '북구');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (47, '??구광?��?��', '?��?���??');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (48, '??구광?��?��', '?��?���??');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (49, '??구광?��?��', '?��?���??');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (50, '??구광?��?��', '군위�??');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (51, '경기?��', '?��?��?��');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (52, '경기?��', '?��?��?��');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (53, '경기?��', '?��?���???��');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (54, '경기?��', '?��?��?��');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (55, '경기?��', '�??천시');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (56, '경기?��', '광명?��');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (57, '경기?��', '?��?��?��');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (58, '경기?��', '?��?��천시');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (59, '경기?��', '?��?��?��');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (60, '경기?��', '고양?��');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (61, '경기?��', '과천?��');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (62, '경기?��', '구리?��');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (63, '경기?��', '?��?��주시');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (64, '경기?��', '?��?��?��');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (65, '경기?��', '?��?��?��');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (66, '경기?��', '군포?��');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (67, '경기?��', '?��?��?��');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (68, '경기?��', '?��?��?��');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (69, '경기?��', '?��?��?��');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (70, '경기?��', '?��주시');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (71, '경기?��', '?��천시');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (72, '경기?��', '?��?��?��');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (73, '경기?��', '�???��?��');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (74, '경기?��', '?��?��?��');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (75, '경기?��', '광주?��');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (76, '경기?��', '?��주시');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (77, '경기?��', '?��천시');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (78, '경기?��', '?��주시');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (79, '경기?��', '?��천군');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (80, '경기?��', '�???���??');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (81, '경기?��', '?��?���??');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (82, '강원?��', '춘천?��');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (83, '강원?��', '?��주시');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (84, '강원?��', '강릉?��');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (85, '강원?��', '?��?��?��');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (86, '강원?��', '?��백시');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (87, '강원?��', '?��초시');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (88, '강원?��', '?��척시');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (89, '강원?��', '?��천군');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (90, '강원?��', '?��?���??');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (91, '강원?��', '?��?���??');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (92, '강원?��', '?��창군');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (93, '강원?��', '?��?���??');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (94, '강원?��', '철원�??');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (95, '강원?��', '?��천군');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (96, '강원?��', '?��구군');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (97, '강원?��', '?��?���??');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (98, '강원?��', '고성�??');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (99, '강원?��', '?��?���??');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (100, '충청북도', '�??주시');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (101, '충청북도', '충주?��');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (102, '충청북도', '?��천시');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (103, '충청북도', '보�?�??');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (104, '충청북도', '?��천군');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (105, '충청북도', '?��?���??');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (106, '충청북도', '증평�??');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (107, '충청북도', '진천�??');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (108, '충청북도', '괴산�??');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (109, '충청북도', '?��?���??');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (110, '충청북도', '?��?���??');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (111, '충청?��?��', '천안?��');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (112, '충청?��?��', '공주?��');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (113, '충청?��?��', '보령?��');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (114, '충청?��?��', '?��?��?��');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (115, '충청?��?��', '?��?��?��');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (116, '충청?��?��', '?��?��?��');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (117, '충청?��?��', '계룡?��');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (118, '충청?��?��', '?��진시');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (119, '충청?��?��', '금산�??');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (120, '충청?��?��', '�???���??');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (121, '충청?��?��', '?��천군');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (122, '충청?��?��', '�???���??');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (123, '충청?��?��', '?��?���??');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (124, '충청?��?��', '?��?���??');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (125, '충청?��?��', '?��?���??');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (126, '?��?��북도', '?��주시');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (127, '?��?��북도', '군산?��');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (128, '?��?��북도', '?��?��?��');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (129, '?��?��북도', '?��?��?��');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (130, '?��?��북도', '?��?��?��');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (131, '?��?��북도', '�???��?��');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (132, '?��?��북도', '?��주군');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (133, '?��?��북도', '진안�??');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (134, '?��?��북도', '무주�??');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (135, '?��?��북도', '?��?���??');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (136, '?��?��북도', '?��?���??');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (137, '?��?��북도', '?��창군');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (138, '?��?��북도', '고창�??');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (139, '?��?��북도', '�???���??');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (140, '?��?��?��?��', '목포?��');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (141, '?��?��?��?��', '?��?��?��');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (142, '?��?��?��?��', '?��천시');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (143, '?��?��?��?��', '?��주시');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (144, '?��?��?��?��', '광양?��');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (145, '?��?��?��?��', '?��?���??');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (146, '?��?��?��?��', '곡성�??');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (147, '?��?��?��?��', '구�?�??');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (148, '?��?��?��?��', '고흥�??');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (149, '?��?��?��?��', '보성�??');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (150, '?��?��?��?��', '?��?���??');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (151, '?��?��?��?��', '?��?���??');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (152, '?��?��?��?��', '강진�??');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (153, '?��?��?��?��', '?��?���??');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (154, '?��?��?��?��', '?��?���??');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (155, '?��?��?��?��', '무안�??');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (156, '?��?��?��?��', '?��?���??');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (157, '?��?��?��?��', '?��광군');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (158, '?��?��?��?��', '?��?���??');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (159, '?��?��?��?��', '?��?���??');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (160, '?��?��?��?��', '진도�??');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (161, '?��?��?��?��', '?��?���??');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (162, '경상북도', '?��?��?��');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (163, '경상북도', '경주?��');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (164, '경상북도', '�??천시');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (165, '경상북도', '?��?��?��');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (166, '경상북도', '구�?�시');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (167, '경상북도', '?��주시');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (168, '경상북도', '?��천시');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (169, '경상북도', '?��주시');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (170, '경상북도', '문경?��');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (171, '경상북도', '경산?��');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (172, '경상북도', '군위�??');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (173, '경상북도', '?��?���??');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (174, '경상북도', '�???���??');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (175, '경상북도', '?��?���??');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (176, '경상북도', '?��?���??');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (177, '경상북도', '�???���??');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (178, '경상북도', '고령�??');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (179, '경상북도', '?��주군');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (180, '경상북도', '칠곡�??');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (181, '경상북도', '?��천군');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (182, '경상북도', '봉화�??');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (183, '경상북도', '?��진군');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (184, '경상북도', '?��릉군');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (185, '경상?��?��', '창원?��');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (186, '경상?��?��', '진주?��');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (187, '경상?��?��', '?��?��?��');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (188, '경상?��?��', '?��천시');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (189, '경상?��?��', '�???��?��');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (190, '경상?��?��', '�???��?��');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (191, '경상?��?��', '거제?��');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (192, '경상?��?��', '?��?��?��');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (193, '경상?��?��', '?��?���??');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (194, '경상?��?��', '?��?���??');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (195, '경상?��?��', '창녕�??');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (196, '경상?��?��', '고성�??');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (197, '경상?��?��', '?��?���??');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (198, '경상?��?��', '?��?���??');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (199, '경상?��?��', '?���??�??');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (200, '경상?��?��', '?��?���??');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (201, '경상?��?��', '거창�??');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (202, '경상?��?��', '?��천군');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (203, '?��주특별자치도', '?��주시');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (204, '?��주특별자치도', '?���???��?��');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (205, '?��종특별자치시', '?��종시');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (206, '???��광역?��', '???���??');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (207, '???��광역?��', '?���??');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (208, '???��광역?��', '?���??');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (209, '???��광역?��', '?��?���??');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (210, '???��광역?��', '중구');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (211, '?��?��광역?��', '중구');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (212, '?��?��광역?��', '?���??');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (213, '?��?��광역?��', '?���??');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (214, '?��?��광역?��', '북구');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (215, '?��?��광역?��', '?��주군');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (216, '광주광역?��', '?���??');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (217, '광주광역?��', '?���??');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (218, '광주광역?��', '?���??');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (219, '광주광역?��', '북구');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (220, '광주광역?��', '광산�??');

-- STORE 매장 ?���??
INSERT INTO STORE (STORE_NO, STORE_NAME, STORE_ADDRESS, STORE_PHONE, BUSINESS_HOURS, STORE_RC, STORE_REGION_NO,
                   STORE_INFO, STATUS)
VALUES (SEQ_STORE.NEXTVAL, '�??구샵 ?��로웨?��?��?��?��', '?��?��?��별시 마포�?? ?��미산�?? 155 1�??, �??구샵', '0507-1372-2052', '11:00 - 21:30', 25, 14,
        '�??구�?? ?��?�� 첫걸?��, �??구샵?��?��?��.', 'Y');
INSERT INTO STORE (STORE_NO, STORE_NAME, STORE_ADDRESS, STORE_PHONE, BUSINESS_HOURS, STORE_RC, STORE_REGION_NO,
                   STORE_INFO, STATUS)
VALUES (SEQ_STORE.NEXTVAL, '?��맹상?��', '?��?��?��별시 마포�?? ?��?��컵로25�?? 47 3�??, ?��맹상?��', '0507-1386-1064', '1112:00 - 20:00', 3, 14, '?��?��기�?? 줄이?�� ?��?? 마음?��?�� ?��?��?��
?���?? ?��?��?��?�� �??게이?�� 리필 ?��?��?��?��?��?��?��.', 'Y');
INSERT INTO STORE (STORE_NO, STORE_NAME, STORE_ADDRESS, STORE_PHONE, BUSINESS_HOURS, STORE_RC, STORE_REGION_NO,
                   STORE_INFO, STATUS)
VALUES (SEQ_STORE.NEXTVAL, '?��?���??', '?��?��?��별시 ?��?���?? ?��?��리로14�?? 9 1�??, ?��?���??', '070-4118-0710', '12:00 - 20:00', 6, 4,
        '?��?���??(thepicker)?��, 건강?�� ?��?��?�� ?��?��?�� ?��경에 ?��?��?�� ?��?�� ?��?�� ?��?�� �???��?��?���?? ?��?��?���?? 고르?�� ?��?��?�� ?��미합?��?��.', 'Y');
INSERT INTO STORE (STORE_NO, STORE_NAME, STORE_ADDRESS, STORE_PHONE, BUSINESS_HOURS, STORE_RC, STORE_REGION_NO,
                   STORE_INFO, STATUS)
VALUES (SEQ_STORE.NEXTVAL, '?��?��?��?��', '?��?��?��별시 ???���?? ?��번로6�?? 2 1�??, ?��?��?��?��', '0507-1300-3388', '12:30 - 19:00', 3, 12,
        '?��?��?��?��?�� ?��리�? ?��?��?�� ?��?���??면서 �??구�?? ?��?���?? ?��?��?��?�� ?��?��?�� ?��???��?�� �???��?��?��?��.', 'Y');
INSERT INTO STORE (STORE_NO, STORE_NAME, STORE_ADDRESS, STORE_PHONE, BUSINESS_HOURS, STORE_RC, STORE_REGION_NO,
                   STORE_INFO, STATUS)
VALUES (SEQ_STORE.NEXTVAL, '?��?��?��?��', '?��?��?��별시 강동�?? ?��?���??35�?? 34 1�??, ?��?��?��?��', '0507-1395-3534', '10:30 - 19:00', 12, 25,
        '?��?��?��?��?�� ?��리�? ?��?��?�� ?��?���??면서 �??구�?? ?��?���?? ?��?��?��?�� ?��?��?�� ?��???��?�� �???��?��?��?��.', 'Y');
INSERT INTO STORE (STORE_NO, STORE_NAME, STORE_ADDRESS, STORE_PHONE, BUSINESS_HOURS, STORE_RC, STORE_REGION_NO,
                   STORE_INFO, STATUS)
VALUES (SEQ_STORE.NEXTVAL, '?��구밭', '경기 ?��?��?�� 미사강�??���?? 25 FB329?��, FB330?��, FB33', '0507-1306-9626', '10:30 - 19:00', 27, 68,
        '?��구밭?? 비장?��?���?? ?��?��?��?�� ?���?? �???���???��?�� ?��?��?�� ?��?�� 고체 ?��?��?�� �?? ?��?��?��?��?�� ?��?��?��?�� 브랜?��?��?�� ?��조사 ?��?��?��.', 'Y');
INSERT INTO STORE (STORE_NO, STORE_NAME, STORE_ADDRESS, STORE_PHONE, BUSINESS_HOURS, STORE_RC, STORE_REGION_NO,
                   STORE_INFO, STATUS)
VALUES (SEQ_STORE.NEXTVAL, '?��?��?��?��?��?��', '광주 ?���?? ?��??�??74번길 27 ?��?��?��?��?��?��', '0507-1483-4030', '09:00 - 18:00', 37, 217,
        '?��?��친화?�� ?��?��(비누, 주방?��?�� ?��)?�� ?��?��, ?��매하�?? ?���?? ?��?�� ?��?�� 기증받아 ?��매하?�� 중증?��?��?��?�� 고용?��?��?��.', 'Y');
INSERT INTO STORE (STORE_NO, STORE_NAME, STORE_ADDRESS, STORE_PHONE, BUSINESS_HOURS, STORE_RC, STORE_REGION_NO,
                   STORE_INFO, STATUS)
VALUES (SEQ_STORE.NEXTVAL, '�??구별�??�??', '?���?? ?��주시 ?��?���?? 58 1�??', '064-711-8291', '10:00 - 19:00', 102, 203,
        '?��로웨?��?��?�� 리빙?��, �??구별�??�?? ?�� 몸과 �??구�?? ?��리는 ?��?��?�� 즐거??, ?��?��
?��로웨?��?��?���?? ?��?�� ?��?��?�� ?��?��?��?���?? ?��기농 ?��?��?���?? 직접 ?��?��?��?�� ?��?�� 브랜?�� ?��?��?�� 만나�?? ?�� ?��?��?��?��.', 'Y');
INSERT INTO STORE (STORE_NO, STORE_NAME, STORE_ADDRESS, STORE_PHONE, BUSINESS_HOURS, STORE_RC, STORE_REGION_NO,
                   STORE_INFO, STATUS)
VALUES (SEQ_STORE.NEXTVAL, '?��28 ?��?��브러�?? ?��?��', '?��?��?��별시 ?��?���?? ?��?��?���??12�?? 2', '0507-1414-0198', '11:30 - 20:30', 58, 4,
        '?��?�� ?��?�� ?��름다??, ?��28 ?��?��브러�??, ?��?��?��?��?��.', 'Y');
INSERT INTO STORE (STORE_NO, STORE_NAME, STORE_ADDRESS, STORE_PHONE, BUSINESS_HOURS, STORE_RC, STORE_REGION_NO,
                   STORE_INFO, STATUS)
VALUES (SEQ_STORE.NEXTVAL, '?��?��?���??�??', '?��?��?��?�� ?��?���?? ?��북면 ?��?��?���?? 548 1�?? ?��?��?���??�??', '0507-1337-1858', '11:00 - 18:00', 137, 145,
        '?��로웨?��?��?�� 리필?��& ?���?? �??�??. ?��?? ?��?��, �??구에�?? ?�� ?��?? ?��림살?��. ?��?��?�� ???��감들?�� 만들�?? ?��매하?�� ?��?��?���??게입?��?��.', 'Y');
INSERT INTO STORE (STORE_NO, STORE_NAME, STORE_ADDRESS, STORE_PHONE, BUSINESS_HOURS, STORE_RC, STORE_REGION_NO,
                   STORE_INFO, STATUS)
VALUES (SEQ_STORE.NEXTVAL, '?��?��?��그리?��', '?��?��?��별시 마포�?? ?��?��리로 44 5�?? 리�??��?��', '1522-5710', '10:00 - 16:00', 51, 14,
        '?��?��?��?�� ?��?? ?��?��?��중한 ?��?��?�� ?��?�� ?��?��?���?? ?��?��리고?�� ?��?��?�� ?��?��벤처�?? ?��?��?��그리?�� ?��?�� ?���?? 브랜?���?? ?��분해 �???��?�� ?��?��?��?��?�� ?��?��, ?���?? ?���?? ?���?? ?��거하?�� ?��?��?��?��?�� ?��?��?�� �???�� �???��?�� ?��?�� ?��?��?��?�� 만들?�� 갑니?��.', 'Y');
INSERT INTO STORE (STORE_NO, STORE_NAME, STORE_ADDRESS, STORE_PHONE, BUSINESS_HOURS, STORE_RC, STORE_REGION_NO,
                   STORE_INFO, STATUS)
VALUES (SEQ_STORE.NEXTVAL, '천연?��?��?�� �???��?��', '�???��광역?�� 북구 ?���??1�?? 93 2�??', '051-338-9619', '10:30 - 19:00', 93, 33,
        '?��경오?��?�� 줄이?�� ?��?��, ?��?��?���??, �???�� 최초 ?��로웨?��?��?��?��', 'Y');
INSERT INTO STORE (STORE_NO, STORE_NAME, STORE_ADDRESS, STORE_PHONE, BUSINESS_HOURS, STORE_RC, STORE_REGION_NO,
                   STORE_INFO, STATUS)
VALUES (SEQ_STORE.NEXTVAL, '?��?��?��리얼 모레?��?��', '?��?�� ?��?���?? ?��?���??1?���?? 5 ?��?��그라?��?�� 7�??', '070-8633-1333', '09:00 - 19:00', 37, 4,
        '?��?�� �?? ?��?��?�� ?��각하?�� �???���???��?�� 책임?���??, 모레?��?��.', 'Y');
INSERT INTO STORE (STORE_NO, STORE_NAME, STORE_ADDRESS, STORE_PHONE, BUSINESS_HOURS, STORE_RC, STORE_REGION_NO,
                   STORE_INFO, STATUS)
VALUES (SEQ_STORE.NEXTVAL, '비누?��', '경기?�� 군포?�� ?��?���?? 2 LT?���?? ?��카이비즈 1412?��, 1413?��', '0507-1387-0513', '10:00 - 18:00', 62, 66,
        '?��?��?��경과 건강?�� ?��각한 비누�?? 만듭?��?��.', 'Y');
COMMIT;