DROP TABLE STORE_LIKES;
DROP TABLE STORE;
DROP TABLE STORE_ATTA;
DROP TABLE STORE_REGION;
DROP TABLE PRODUCT;
DROP TABLE PAYMENT;
DROP TABLE TB_CATEGORY;
DROP TABLE NOTICE;
DROP TABLE QNA;
DROP TABLE MEMBER;
DROP TABLE TB_CODE;
DROP TABLE TB_CHA_FILE;
DROP TABLE TB_CH_DETAIL_INFO;
DROP TABLE LIKES;
DROP TABLE REPORT;
DROP TABLE FAQ;
DROP TABLE PRODUCT_ATTA;
DROP TABLE DY_BOARD;
DROP TABLE GRADE;
DROP TABLE DY_REPLY;
DROP TABLE TB_CH_CON_REPLY;
DROP TABLE REVIEW;
DROP TABLE REVIEW_REPLY;
DROP TABLE ORDERS;
DROP TABLE POINT;
DROP TABLE CART;
DROP TABLE TB_GRP_CODE;
DROP TABLE TB_CATEGORY_TEMPLATE;
DROP TABLE TB_CH_CONFIRM;
DROP TABLE TB_CHALLENGE;
DROP TABLE Q_REPLY;

DROP SEQUENCE SEQ_TB_CHALLENGE;
DROP SEQUENCE SEQ_STORE;
DROP SEQUENCE SEQ_STORE_LIKES;
DROP SEQUENCE SEQ_STORE_ATTA;
DROP SEQUENCE SEQ_PRODUCT;
DROP SEQUENCE SEQ_PAYMENT;
DROP SEQUENCE SEQ_TB_CATEGORY;
DROP SEQUENCE SEQ_NOTICE;
DROP SEQUENCE SEQ_TB_CATEGORY_TEMPLATE;
DROP SEQUENCE SEQ_QNA;
DROP SEQUENCE SEQ_MEMBER;
DROP SEQUENCE SEQ_TB_GRP_CODE;
DROP SEQUENCE SEQ_TB_CODE;
DROP SEQUENCE SEQ_TB_CHA_FILE;
DROP SEQUENCE SEQ_TB_CH_CONFIRM;
DROP SEQUENCE SEQ_TB_CH_DETAIL_INFO;
DROP SEQUENCE SEQ_LIKE;
DROP SEQUENCE SEQ_REPORT;
DROP SEQUENCE SEQ_FAQ;
DROP SEQUENCE SEQ_PRODUCT_ATTA;
DROP SEQUENCE SEQ_DY_BOARD;
DROP SEQUENCE SEQ_GRADE;
DROP SEQUENCE SEQ_DY_REPLY;
DROP SEQUENCE SEQ_TB_CH_CON_REPLY;
DROP SEQUENCE SEQ_REVIEW;
DROP SEQUENCE SEQ_REVIEW_REPLY;
DROP SEQUENCE SEQ_ORDER;
DROP SEQUENCE SEQ_POINT;
DROP SEQUENCE SEQ_CART;
DROP SEQUENCE SEQ_Q_REPLY;

CREATE TABLE TB_CHALLENGE
(
    CH_NO        NUMBER NOT NULL,
    CH_TITLE     VARCHAR2(100) NOT NULL,
    CH_START_DAY VARCHAR2(8) NOT NULL,
    CH_END_DAY   VARCHAR2(8) NOT NULL,
    MEMBER_ID    VARCHAR2(100) NOT NULL,
    CATEGORY_NO  NUMBER NOT NULL,
    FILE_NO      NUMBER NOT NULL,
    CODE         VARCHAR2(8) NOT NULL,
    CH_CONTENT   CLOB NOT NULL
);

CREATE SEQUENCE SEQ_TB_CHALLENGE;

CREATE TABLE STORE_REGION
(
    STORE_REGION_NO NUMBER PRIMARY KEY,
    CITY            VARCHAR2(50),
    PROVINCES       VARCHAR2(50),
    CONSTRAINT city_province_unique UNIQUE (CITY, PROVINCES)
);


CREATE TABLE STORE
(
    STORE_NO        NUMBER  PRIMARY KEY,
    STORE_NAME      VARCHAR2(50) NOT NULL,
    STORE_ADDRESS   VARCHAR2(200) NOT NULL,
    STORE_DETAIL_ADDRESS VARCHAR2(200) NOT NULL,
    STORE_PHONE     VARCHAR2(30) NULL,
    BUSINESS_HOURS  VARCHAR2(20) NULL,
    STORE_LIKES     NUMBER DEFAULT 0 NOT NULL,
    STORE_LAT       NUMBER NULL,
    STORE_LON       NUMBER NULL,
    STORE_REGION_NO NUMBER NULL,
    STORE_INFO      VARCHAR2(500),
    STATUS       CHAR(1) DEFAULT 'Y'     NOT NULL,
    FOREIGN KEY (STORE_REGION_NO) REFERENCES STORE_REGION (STORE_REGION_NO),
    CONSTRAINT UNQ_STORE_ADDRESS UNIQUE (STORE_ADDRESS, STORE_DETAIL_ADDRESS)
);

CREATE SEQUENCE SEQ_STORE;

CREATE TABLE STORE_LIKES
(   
    STORE_LIKES_NO NUMBER PRIMARY KEY,
    MEMBER_ID  VARCHAR2(100) NOT NULL,
    STORE_NO NUMBER,
    FOREIGN KEY (STORE_NO) REFERENCES STORE (STORE_NO)
);

CREATE SEQUENCE SEQ_STORE_LIKES;

CREATE TABLE STORE_ATTA
(
    ATTACHMENT_NO NUMBER NOT NULL,
    CHANGER_NAME  VARCHAR2(255) NOT NULL,
    FILE_LEVEL    NUMBER NOT NULL,
    STORE_NO    NUMBER NOT NULL
);

CREATE SEQUENCE SEQ_STORE_ATTA;


CREATE TABLE PRODUCT
(
    PRODUCT_NO   NUMBER                  NOT NULL,
    PRODUCT_NAME VARCHAR2(100) NOT NULL,
    CATEGORY     VARCHAR2(20) NOT NULL,
    PRODUCT_INFO VARCHAR2(1000) NOT NULL,
    PRICE        NUMBER                  NOT NULL,
    DISCOUNT     NUMBER  DEFAULT 0       NOT NULL,
    STOCK        NUMBER  DEFAULT 0       NOT NULL,
    CREATE_DATE  DATE    DEFAULT SYSDATE NOT NULL,
    STATUS       CHAR(1) DEFAULT 'Y'     NOT NULL
);

CREATE SEQUENCE SEQ_PRODUCT;

CREATE TABLE PAYMENT
(
    PAYMENT_NO             VARCHAR2(20) NOT NULL,
    MEMBER_ID              VARCHAR2(100) NOT NULL,
    PAYMENT_DATE           DATE DEFAULT SYSDATE NULL,
    PAYMENT_TYPE           VARCHAR2(20) NOT NULL,
    STATUS                 VARCHAR2(1) NOT NULL,
    PAYMENT_NAME           VARCHAR2(100) NOT NULL,
    PAYMENT_TOTAL          NUMBER NOT NULL,
    RECEIVE_NAME           VARCHAR2(20) NOT NULL,
    RECEIVE_PHONE          VARCHAR2(11) NOT NULL,
    POST_CODE              VARCHAR2(5) NOT NULL,
    ADDRESS1               VARCHAR2(100) NOT NULL,
    ADDRESS2               VARCHAR2(100) NOT NULL,
    DELIVERY_COMMENT       VARCHAR2(100) DEFAULT '없음',
    PAYMENT_TOKEN          VARCHAR2(40) NOT NULL,
    REWARD_POINT           NUMBER NOT NULL
);

CREATE SEQUENCE SEQ_PAYMENT;

CREATE TABLE TB_CATEGORY
(
    CATEGORY_NO   NUMBER NOT NULL,
    CATEGORY_NAME VARCHAR2(100) NOT NULL,
    STATUS        VARCHAR2(1) DEFAULT 'Y' NOT NULL
);

CREATE SEQUENCE SEQ_TB_CATEGORY;

CREATE TABLE NOTICE
(
    NOTICE_NO       NUMBER                  NOT NULL,
    NOTICE_TITLE    VARCHAR2(1000) NOT NULL,
    NOTICE_CONTENT  VARCHAR2(4000) NOT NULL,
    NOTICE_DATE    DATE    DEFAULT SYSDATE NOT NULL,
    STATUS          CHAR(1) DEFAULT 'Y'     NOT NULL,
    NOTICE_CATEGORY VARCHAR2(15) NOT NULL,
    NOTICE_VIEW     NUMBER  DEFAULT 0       NOT NULL
);

CREATE SEQUENCE SEQ_NOTICE;

CREATE TABLE TB_CATEGORY_TEMPLATE
(
    CATEGORY_TEMPLATE_NO NUMBER NOT NULL,
    INPUT_TYPE           VARCHAR2(20) NOT NULL,
    STATUS               VARCHAR2(1) DEFAULT 'Y' NOT NULL,
    SORT_NO              NUMBER NOT NULL,
    CH_SUB_TITLE         VARCHAR2(200) NULL,
    GRP_CODE             VARCHAR2(8) NOT NULL,
    CATEGORY_NO          NUMBER NOT NULL
);

CREATE SEQUENCE SEQ_TB_CATEGORY_TEMPLATE;

CREATE TABLE QNA
(
    BOARD_NO      NUMBER               NOT NULL,
    BOARD_TITLE   VARCHAR2(100) NOT NULL,
    BOARD_CONTENT VARCHAR(2000)        NOT NULL,
    BOARD_DATE    DATE DEFAULT SYSDATE NOT NULL,
    BOARD_REPLY   VARCHAR(1000) NULL,
    MEMBER_ID     VARCHAR2(100) NOT NULL,
    ORIGIN_NAME      VARCHAR2(100) NOT NULL,
    CHANGE_NAME      VARCHAR2(100) NOT NULL,
    STATUS	VARCHAR2(1)	NOT NULL DEFAULT 'Y'

);

CREATE SEQUENCE SEQ_QNA;

CREATE TABLE MEMBER
(
    MEMBER_ID    VARCHAR2(100) NOT NULL,
    MEMBER_PWD   VARCHAR2(100) NOT NULL,
    MEMBER_NAME  VARCHAR2(50) NOT NULL,
    EMAIL        VARCHAR2(30) NOT NULL,
    BIRTH_DATE   DATE NULL,
    PHONE        CHAR(11)                NOT NULL,
    GENDER       CHAR(1) NULL,
    CREATED_DATE DATE    DEFAULT SYSDATE NOT NULL,
    STATUS       CHAR(1) DEFAULT 'Y'     NOT NULL,
    TOTAL_PAY    NUMBER  DEFAULT 0       NOT NULL,
    ADDRESS1     VARCHAR2(255) NOT NULL,
    ADDRESS2     VARCHAR2(255) NOT NULL,
    GRADE_NAME	 VARCHAR2(15) DEFAULT 'RED',
    POST_CODE	 VARCHAR2(5) NOT NULL,
    MAIL_AUTH	 NUMBER DEFAULT 0,
    MAIL_KEY	 VARCHAR2(50),
    TOTAL_POINT	 NUMBER DEFAULT 1000,
    MEMBER_IMG	 VARCHAR2(300) DEFAULT 'logo.png'
);

CREATE SEQUENCE SEQ_MEMBER;

CREATE TABLE TB_GRP_CODE
(
    GRP_CODE      VARCHAR2(8) NOT NULL,
    GRP_CODE_NAME VARCHAR2(100) NOT NULL,
    STATUS        VARCHAR2(1) DEFAULT 'Y' NOT NULL
);

CREATE SEQUENCE SEQ_TB_GRP_CODE;

CREATE TABLE TB_CODE
(
    CODE      VARCHAR2(8) NOT NULL,
    GRP_CODE  VARCHAR2(8) NOT NULL,
    CODE_NAME VARCHAR2(100) NOT NULL,
    STATUS    VARCHAR2(1) DEFAULT 'Y' NOT NULL,
    SORT_NO   NUMBER NOT NULL
);

CREATE SEQUENCE SEQ_TB_CODE;

CREATE TABLE TB_CHA_FILE
(
    FILE_NO   NUMBER NOT NULL,
    FILE_NAME VARCHAR2(100) NOT NULL,
    FILE_PATH VARCHAR2(300) NOT NULL
);

CREATE SEQUENCE SEQ_TB_CHA_FILE;


CREATE TABLE TB_CH_CONFIRM
(
    CH_CON_NO          NUMBER               NOT NULL,
    CH_NO              NUMBER               NOT NULL,
    CH_CON_TITLE       VARCHAR2(200) NOT NULL,
    CH_CON_CONTENT     VARCHAR2(4000) NOT NULL,
    MEMBER_ID          VARCHAR2(100) NOT NULL,
    STATUS             VARCHAR2(1) DEFAULT 'Y' NOT NULL,
    CH_CON_CREATE_DATE DATE DEFAULT SYSDATE NOT NULL
);

CREATE SEQUENCE SEQ_TB_CH_CONFIRM;

CREATE TABLE TB_CH_DETAIL_INFO
(
    CH_DETAIL_INFO_NO    NUMBER NOT NULL,
    CH_NO                NUMBER NOT NULL,
    CH_CON_NO            NUMBER NOT NULL,
    CATEGORY_TEMPLATE_NO NUMBER NOT NULL,
    CH_DETAIL_INFO_DATA  VARCHAR2(4000) NOT NULL,
    STATUS               VARCHAR2(1) DEFAULT 'Y' NOT NULL,
    CODE                 VARCHAR2(8) NOT NULL,
    FILE_NO              NUMBER NOT NULL
);

CREATE SEQUENCE SEQ_TB_CH_DETAIL_INFO;

CREATE TABLE LIKES
(
    MEMBER_ID  VARCHAR2(100) NOT NULL,
    PRODUCT_NO NUMBER NOT NULL
);

CREATE SEQUENCE SEQ_LIKE;

CREATE TABLE REPORT
(
    REPORT_NO      NUMBER NOT NULL,
    REPORT_CONTENT VARCHAR2(3000) NOT NULL,
    CH_CON_NO      NUMBER NOT NULL,
    CH_NO          NUMBER NOT NULL,
    DY_BOARD_NO    NUMBER NOT NULL,
    MEMBER_ID      VARCHAR2(100) NOT NULL
);

CREATE SEQUENCE SEQ_REPORT;

CREATE TABLE FAQ
(
    FAQ_NO       NUMBER        NOT NULL,
    FAQ_QUESTION VARCHAR2(100) NOT NULL,
    FAQ_ANSWER   VARCHAR(2000) NOT NULL,
    FAQ_CATEGORY VARCHAR(50)   NOT NULL
);

CREATE SEQUENCE SEQ_FAQ;

CREATE TABLE PRODUCT_ATTA
(
    ATTACHMENT_NO NUMBER NOT NULL,
    CHANGER_NAME  VARCHAR2(255) NOT NULL,
    FILE_LEVEL    NUMBER NOT NULL,
    PRODUCT_NO    NUMBER NOT NULL
);

CREATE SEQUENCE SEQ_PRODUCT_ATTA;

CREATE TABLE DY_BOARD
(
    DY_BOARD_NO      NUMBER NOT NULL,
    DY_BOARD_TITLE   VARCHAR2(100) NOT NULL,
    DY_BOARD_CONTENT VARCHAR2(4000) NOT NULL,
    DY_CREATE_DATE   DATE   DEFAULT SYSDATE NULL,
    DY_STATUS        VARCHAR2(1) DEFAULT 'Y' NULL,
    DY_COUNT         NUMBER DEFAULT 0 NULL,
    ORIGIN_NAME      VARCHAR2(100) NOT NULL,
    CHANGE_NAME      VARCHAR2(100) NOT NULL,
    MEMBER_ID        VARCHAR2(100) NOT NULL,
    DY_LIKE         NUMBER DEFAULT 0 NOT NULL
);

CREATE SEQUENCE SEQ_DY_BOARD;

CREATE TABLE GRADE
(
    GRADE_NAME  VARCHAR2(15) DEFAULT 'RED' NOT NULL,
    PAYMENT_MIN NUMBER NOT NULL,
    PAYMENT_MAX NUMBER NOT NULL
);

CREATE SEQUENCE SEQ_GRADE;

CREATE TABLE DY_REPLY
(
    DY_REPLY_NO      NUMBER               NOT NULL,
    DY_BOARD_NO      NUMBER               NOT NULL,
    DY_REPLY_CONTENT VARCHAR2(400) NOT NULL,
    DY_CREATE_DATE   DATE DEFAULT SYSDATE NOT NULL,
    DY_STATUS        VARCHAR2(1) DEFAULT 'Y' NULL,
    MEMBER_ID        VARCHAR2(100) NOT NULL
);

CREATE SEQUENCE SEQ_DY_REPLY;

CREATE TABLE TB_CH_CON_REPLY
(
    RE_NO          NUMBER               NOT NULL,
    CH_CON_NO      NUMBER               NOT NULL,
    CH_NO          NUMBER               NOT NULL,
    RE_CONTENT     VARCHAR2(2000) NOT NULL,
    RE_CREATE_DATE DATE DEFAULT SYSDATE NOT NULL,
    STATUS         VARCHAR2(1) DEFAULT 'Y' NOT NULL,
    MEMBER_ID      VARCHAR2(100) NOT NULL
);

CREATE SEQUENCE SEQ_TB_CH_CON_REPLY;

CREATE TABLE REVIEW
(
    REVIEW_NO      NUMBER               NOT NULL,
    REVIEW_CONTENT VARCHAR2(1000) NOT NULL,
    CREATE_DATE    DATE DEFAULT SYSDATE NOT NULL,
    RATING         NUMBER               NOT NULL,
    CHANGE_NAME    VARCHAR2(255) NULL,
    PRODUCT_NO     NUMBER               NOT NULL,
    MEMBER_ID      VARCHAR2(100) NOT NULL
    COUNT          NUMBER DEFAULT 0 NOT NULL
);

CREATE SEQUENCE SEQ_REVIEW;

CREATE TABLE REVIEW_REPLY
(
    RV_REPLY_NO   NUMBER                  NOT NULL,
    REPLY_CONTENT VARCHAR2(1000) NOT NULL,
    CREATED_DATE  DATE    DEFAULT SYSDATE NOT NULL,
    STATUS        CHAR(1) DEFAULT 'Y'     NOT NULL,
    REVIEW_NO     NUMBER                  NOT NULL,
    MEMBER_ID     VARCHAR2(100) NOT NULL
);

CREATE SEQUENCE SEQ_REVIEW_REPLY;

CREATE TABLE ORDERS
(
    ORDER_NO       NUMBER           NOT NULL,
    PRODUCT_AMOUNT NUMBER DEFAULT 1 NOT NULL,
    PAYMENT_NO     NUMBER           NOT NULL,
    PRODUCT_NO     NUMBER           NOT NULL
);

CREATE SEQUENCE SEQ_ORDER;

CREATE TABLE POINT
(
    POINT_NO      NUMBER               NOT NULL,
    POINT_CONTENT VARCHAR2(300) NOT NULL,
    POINT_NUM     NUMBER               NOT NULL,
    STATUS        CHAR(3)              NOT NULL,
    POINT_DATE    DATE DEFAULT SYSDATE NOT NULL,
    MEMBER_ID     VARCHAR2(100) NOT NULL
);

CREATE SEQUENCE SEQ_POINT;

CREATE TABLE CART
(
    CART_NO    NUMBER NOT NULL,
    AMOUNT     NUMBER NOT NULL,
    PRICE      NUMBER NOT NULL,
    PRODUCT_NO NUMBER NOT NULL,
    MEMBER_ID  VARCHAR2(100) NOT NULL
);

CREATE SEQUENCE SEQ_CART;

CREATE TABLE Q_REPLY
(
    Q_REPLY_NO NUMBER NOT NULL,
    BOARD_NO NUMBER NOT NULL,
    Q_REPLY_CONTENT VARCHAR2(400) NOT NULL,
    Q_CREATE_DATE DATE DEFAULT SYSDATE NOT NULL,
    STATUS VARCHAR2(1) DEFAULT 'Y',
    MEMBER_ID VARCHAR2(100) NOT NULL
);

CREATE SEQUENCE SEQ_Q_REPLY;

ALTER TABLE TB_CHALLENGE
    ADD CONSTRAINT PK_TB_CHALLENGE PRIMARY KEY (CH_NO);

ALTER TABLE STORE
    ADD CONSTRAINT PK_STORE PRIMARY KEY (STORE_NO);

ALTER TABLE PRODUCT
    ADD CONSTRAINT PK_PRODUCT PRIMARY KEY (PRODUCT_NO);

ALTER TABLE PAYMENT
    ADD CONSTRAINT PK_PAYMENT PRIMARY KEY (PAYMENT_NO);

ALTER TABLE TB_CATEGORY
    ADD CONSTRAINT PK_TB_CATEGORY PRIMARY KEY (CATEGORY_NO);

ALTER TABLE NOTICE
    ADD CONSTRAINT PK_NOTICE PRIMARY KEY (NOTICE_NO);

ALTER TABLE TB_CATEGORY_TEMPLATE
    ADD CONSTRAINT PK_TB_CATEGORY_TEMPLATE PRIMARY KEY (CATEGORY_TEMPLATE_NO);

ALTER TABLE QNA
    ADD CONSTRAINT PK_QNA PRIMARY KEY (BOARD_NO);

ALTER TABLE MEMBER
    ADD CONSTRAINT PK_MEMBER PRIMARY KEY (MEMBER_ID);

ALTER TABLE TB_GRP_CODE
    ADD CONSTRAINT PK_TB_GRP_CODE PRIMARY KEY (GRP_CODE);

ALTER TABLE TB_CODE
    ADD CONSTRAINT PK_TB_CODE PRIMARY KEY (CODE, GRP_CODE);

ALTER TABLE TB_CHA_FILE
    ADD CONSTRAINT PK_TB_CHA_FILE PRIMARY KEY (FILE_NO);

ALTER TABLE TB_CH_CONFIRM
    ADD CONSTRAINT PK_TB_CH_CONFIRM PRIMARY KEY (CH_CON_NO, CH_NO);

ALTER TABLE TB_CH_DETAIL_INFO
    ADD CONSTRAINT PK_TB_CH_DETAIL_INFO PRIMARY KEY (CH_DETAIL_INFO_NO, CH_CON_NO, CH_NO, CATEGORY_TEMPLATE_NO);

ALTER TABLE REPORT
    ADD CONSTRAINT PK_REPORT PRIMARY KEY (REPORT_NO);

ALTER TABLE FAQ
    ADD CONSTRAINT PK_FAQ PRIMARY KEY (FAQ_NO);

ALTER TABLE STORE_ATTA
    ADD CONSTRAINT PK_STORE_ATTA PRIMARY KEY (FILE_NO);

ALTER TABLE PRODUCT_ATTA
    ADD CONSTRAINT PK_PRODUCT_ATTA PRIMARY KEY (ATTACHMENT_NO);

ALTER TABLE DY_BOARD
    ADD CONSTRAINT PK_DY_BOARD PRIMARY KEY (DY_BOARD_NO);

ALTER TABLE GRADE
    ADD CONSTRAINT PK_GRADE PRIMARY KEY (GRADE_NAME);

ALTER TABLE DY_REPLY
    ADD CONSTRAINT PK_DY_REPLY PRIMARY KEY (DY_REPLY_NO);

ALTER TABLE TB_CH_CON_REPLY
    ADD CONSTRAINT PK_TB_CH_CON_REPLY PRIMARY KEY (RE_NO, CH_CON_NO, CH_NO);

ALTER TABLE REVIEW
    ADD CONSTRAINT PK_REVIEW PRIMARY KEY (REVIEW_NO);

ALTER TABLE REVIEW_REPLY
    ADD CONSTRAINT PK_REVIEW_REPLY PRIMARY KEY (RV_REPLY_NO);

ALTER TABLE ORDERS
    ADD CONSTRAINT PK_ORDER PRIMARY KEY (ORDER_NO);

ALTER TABLE POINT
    ADD CONSTRAINT PK_POINT PRIMARY KEY (POINT_NO);

ALTER TABLE CART
    ADD CONSTRAINT PK_CART PRIMARY KEY (CART_NO);

ALTER TABLE Q_REPLY 
ADD CONSTRAINT PK_Q_REPLY PRIMARY KEY (Q_REPLY_NO);



ALTER TABLE TB_CODE
    ADD CONSTRAINT FK_TB_GRP_CODE FOREIGN KEY (GRP_CODE)
        REFERENCES TB_GRP_CODE (GRP_CODE);

ALTER TABLE TB_CH_CONFIRM
    ADD CONSTRAINT FK_TB_CHALLENGE FOREIGN KEY (CH_NO)
        REFERENCES TB_CHALLENGE (CH_NO);

ALTER TABLE TB_CH_DETAIL_INFO
    ADD CONSTRAINT FK_TB_CHALLENGE2 FOREIGN KEY (CH_NO)
        REFERENCES TB_CHALLENGE (CH_NO);

ALTER TABLE TB_CH_DETAIL_INFO
    ADD CONSTRAINT FK_TB_CATEGORY_TEMPLATE FOREIGN KEY (CATEGORY_TEMPLATE_NO)
        REFERENCES TB_CATEGORY_TEMPLATE (CATEGORY_TEMPLATE_NO);

ALTER TABLE TB_CH_CON_REPLY
    ADD CONSTRAINT FK_TB_CH_CONFIRM1 FOREIGN KEY (CH_CON_NO, CH_NO)
        REFERENCES TB_CH_CONFIRM (CH_CON_NO, CH_NO);




------------------- [ 챌린지관련 시작 ] ------------------- 
-- < 제약조건 변경사항 >

ALTER TABLE TB_CH_DETAIL_INFO
DROP
CONSTRAINT SYS_C0010294;


ALTER TABLE TB_CH_DETAIL_INFO
DROP
CONSTRAINT SYS_C0010295;


---------------------------------------------------------------------------------------
--  < 시퀀스 변경사항 >
-- 1. TB_CATEGORY 시퀀스
DROP SEQUENCE SEQ_CATE_NO;

CREATE SEQUENCE SEQ_CATE_NO
    START WITH 10000000;

SELECT SEQ_CATE_NO.NEXTVAL
FROM DUAL;


-- 2. TB_CATEGORY_TEMPLATE 시퀀스 
DROP SEQUENCE SEQ_TB_CATEGORY_TEMPLATE;

CREATE SEQUENCE SEQ_TB_CATEGORY_TEMPLATE
    START WITH 10000000;

SELECT SEQ_TB_CATEGORY_TEMPLATE.NEXTVAL
FROM DUAL;


-----------------------------------------------------------------------------------
-- < 컬럼 변경사항 >

ALTER TABLE TB_CHALLENGE DROP COLUMN CODE;

ALTER TABLE TB_CATEGORY_TEMPLATE DROP COLUMN GRP_CODE;

------------------------------------------------------------------------------------
-- < 코멘트 >
-- 1. TB_CATEGORY
COMMENT
ON COLUMN TB_CATEGORY.CATEGORY_NO IS '카테고리 일련번호';
COMMENT
ON COLUMN TB_CATEGORY.CATEGORY_NAME IS '카테고리명';
COMMENT
ON COLUMN TB_CATEGORY.STATUS IS '사용여부';

-- 2. TB_CATEGORY_TEMPLATE
COMMENT
ON COLUMN TB_CATEGORY_TEMPLATE.CATEGORY_TEMPLATE_NO IS '탬플릿 일련번호';
COMMENT
ON COLUMN TB_CATEGORY_TEMPLATE.INPUT_TYPE IS '입력타입';
COMMENT
ON COLUMN TB_CATEGORY_TEMPLATE.STATUS IS '사용여부';
COMMENT
ON COLUMN TB_CATEGORY_TEMPLATE.SORT_NO IS '우선순위';
COMMENT
ON COLUMN TB_CATEGORY_TEMPLATE.CH_SUB_TITLE IS '챌린지 소제목';
COMMENT
ON COLUMN TB_CATEGORY_TEMPLATE.CATEGORY_NO IS '카테고리 일련번호';

-- 3. TB_CH_CON_REPLY
COMMENT
ON COLUMN TB_CH_CON_REPLY.RE_NO IS '댓글번호';
COMMENT
ON COLUMN TB_CH_CON_REPLY.CH_CON_NO IS '챌린지 인증 일련번호';
COMMENT
ON COLUMN TB_CH_CON_REPLY.CH_NO IS '챌린지 일련번호';
COMMENT
ON COLUMN TB_CH_CON_REPLY.RE_CONTENT IS '댓글내용';
COMMENT
ON COLUMN TB_CH_CON_REPLY.RE_CREATE_DATE IS '작성일';
COMMENT
ON COLUMN TB_CH_CON_REPLY.STATUS IS '사용여부';
COMMENT
ON COLUMN TB_CH_CON_REPLY.MEMBER_ID IS '회원아이디';

-- 4. TB_CH_CONFIRM
COMMENT
ON COLUMN TB_CH_CONFIRM.CH_CON_NO IS '챌린지 인증 일련번호';
COMMENT
ON COLUMN TB_CH_CONFIRM.CH_NO IS '챌린지 일련번호';
COMMENT
ON COLUMN TB_CH_CONFIRM.CH_CON_TITLE IS '챌린지 인증 제목';
COMMENT
ON COLUMN TB_CH_CONFIRM.CH_CON_CONTENT IS '챌린지 인증 내용';
COMMENT
ON COLUMN TB_CH_CONFIRM.MEMBER_ID IS '회원아이디';
COMMENT
ON COLUMN TB_CH_CONFIRM.STATUS IS '사용여부';
COMMENT
ON COLUMN TB_CH_CONFIRM.CH_CON_CREATE_DATE IS '작성일';

-- 5. TB_CH_DETAIL_INFO
COMMENT
ON COLUMN TB_CH_DETAIL_INFO.CH_DETAIL_INFO_NO IS '챌린지 상세정보 일련번호';
COMMENT
ON COLUMN TB_CH_DETAIL_INFO.CH_NO IS '챌린지 일련번호';
COMMENT
ON COLUMN TB_CH_DETAIL_INFO.CATEGORY_TEMPLATE_NO IS '탬플릿 일련번호';
COMMENT
ON COLUMN TB_CH_DETAIL_INFO.CH_DETAIL_INFO_DATA IS '챌린지 상세정보 데이터';
COMMENT
ON COLUMN TB_CH_DETAIL_INFO.STATUS IS '사용여부';
COMMENT
ON COLUMN TB_CH_DETAIL_INFO.CODE IS '코드';
COMMENT
ON COLUMN TB_CH_DETAIL_INFO.FILE_NO IS '파일 일련번호';

-- 6. TB_CHA_FILE
COMMENT
ON COLUMN TB_CHA_FILE.FILE_NO IS '파일 일련번호';
COMMENT
ON COLUMN TB_CHA_FILE.FILE_NAME IS '파일명';
COMMENT
ON COLUMN TB_CHA_FILE.FILE_PATH IS '파일경로';

-- 7. TB_CHALLENGE
COMMENT
ON COLUMN TB_CHALLENGE.CH_NO IS '챌린지 일련번호';
COMMENT
ON COLUMN TB_CHALLENGE.CH_TITLE IS '챌린지명';
COMMENT
ON COLUMN TB_CHALLENGE.CH_START_DAY IS '챌린지 시작일';
COMMENT
ON COLUMN TB_CHALLENGE.CH_END_DAY IS '챌린지 종료일';
COMMENT
ON COLUMN TB_CHALLENGE.MEMBER_ID IS '회원아이디';
COMMENT
ON COLUMN TB_CHALLENGE.CATEGORY_NO IS '카테고리 일련번호';
COMMENT
ON COLUMN TB_CHALLENGE.FILE_NO IS '파일 일련번호';

-- 8. TB_CODE
COMMENT
ON COLUMN TB_CODE.CODE IS '코드';
COMMENT
ON COLUMN TB_CODE.GRP_CODE IS '그룹코드';
COMMENT
ON COLUMN TB_CODE.CODE_NAME IS '코드명';
COMMENT
ON COLUMN TB_CODE.STATUS IS '사용여부';
COMMENT
ON COLUMN TB_CODE.SORT_NO IS '우선순위';


-- 9. TB_GRP_CODE
COMMENT
ON COLUMN TB_GRP_CODE.GRP_CODE IS '그룹코드';
COMMENT
ON COLUMN TB_GRP_CODE.GRP_CODE_NAME IS '그룹코드명';
COMMENT
ON COLUMN TB_GRP_CODE.STATUS IS '사용여부';
------------------- [ 챌린지관련 끝 ] ------------------- 

-- GRADE 더미
INSERT INTO GRADE (GRADE_NAME, PAYMENT_MIN, PAYMENT_MAX)
VALUES ('RED', 0, 99999);
INSERT INTO GRADE (GRADE_NAME, PAYMENT_MIN, PAYMENT_MAX)
VALUES ('ORANGE', 100000, 499999);
INSERT INTO GRADE (GRADE_NAME, PAYMENT_MIN, PAYMENT_MAX)
VALUES ('GREEN', 500000, 999999);
INSERT INTO GRADE (GRADE_NAME, PAYMENT_MIN, PAYMENT_MAX)
VALUES ('BLUE', 1000000, 2147483647);

-- STORE_REGION 더미
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (1, '서울', '종로구');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (2, '서울', '중구');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (3, '서울', '용산구');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (4, '서울', '성동구');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (5, '서울', '광진구');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (6, '서울', '동대문구');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (7, '서울', '중랑구');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (8, '서울', '성북구');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (9, '서울', '강북구');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (10, '서울', '도봉구');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (11, '서울', '노원구');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (12, '서울', '은평구');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (13, '서울', '서대문구');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (14, '서울', '마포구');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (15, '서울', '양천구');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (16, '서울', '강서구');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (17, '서울', '구로구');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (18, '서울', '금천구');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (19, '서울', '영등포구');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (20, '서울', '동작구');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (21, '서울', '관악구');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (22, '서울', '서초구');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (23, '서울', '강남구');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (24, '서울', '송파구');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (25, '서울', '강동구');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (26, '부산', '중구');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (27, '부산', '서구');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (28, '부산', '동구');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (29, '부산', '영도구');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (30, '부산', '부산진구');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (31, '부산', '동래구');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (32, '부산', '남구');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (33, '부산', '북구');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (34, '부산', '강서구');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (35, '부산', '해운대구');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (36, '부산', '사하구');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (37, '부산', '금정구');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (38, '부산', '연제구');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (39, '부산', '수영구');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (40, '부산', '사상구');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (41, '부산', '기장군');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (42, '대구', '중구');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (43, '대구', '동구');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (44, '대구', '서구');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (45, '대구', '남구');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (46, '대구', '북구');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (47, '대구', '수성구');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (48, '대구', '달서구');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (49, '대구', '달성군');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (50, '대구', '군위군');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (51, '경기', '수원시');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (52, '경기', '성남시');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (53, '경기', '의정부시');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (54, '경기', '안양시');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (55, '경기', '부천시');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (56, '경기', '광명시');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (57, '경기', '평택시');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (58, '경기', '동두천시');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (59, '경기', '안산시');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (60, '경기', '고양시');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (61, '경기', '과천시');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (62, '경기', '구리시');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (63, '경기', '남양주시');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (64, '경기', '오산시');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (65, '경기', '시흥시');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (66, '경기', '군포시');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (67, '경기', '의왕시');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (68, '경기', '하남시');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (69, '경기', '용인시');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (70, '경기', '파주시');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (71, '경기', '이천시');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (72, '경기', '안성시');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (73, '경기', '김포시');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (74, '경기', '화성시');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (75, '경기', '광주시');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (76, '경기', '양주시');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (77, '경기', '포천시');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (78, '경기', '여주시');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (79, '경기', '연천군');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (80, '경기', '가평군');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (81, '경기', '양평군');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (82, '강원특별자치도', '춘천시');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (83, '강원특별자치도', '원주시');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (84, '강원특별자치도', '강릉시');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (85, '강원특별자치도', '동해시');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (86, '강원특별자치도', '태백시');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (87, '강원특별자치도', '속초시');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (88, '강원특별자치도', '삼척시');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (89, '강원특별자치도', '홍천군');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (90, '강원특별자치도', '횡성군');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (91, '강원특별자치도', '영월군');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (92, '강원특별자치도', '평창군');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (93, '강원특별자치도', '정선군');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (94, '강원특별자치도', '철원군');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (95, '강원특별자치도', '화천군');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (96, '강원특별자치도', '양구군');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (97, '강원특별자치도', '인제군');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (98, '강원특별자치도', '고성군');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (99, '강원특별자치도', '양양군');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (100, '충북', '청주시');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (101, '충북', '충주시');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (102, '충북', '제천시');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (103, '충북', '보은군');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (104, '충북', '옥천군');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (105, '충북', '영동군');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (106, '충북', '증평군');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (107, '충북', '진천군');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (108, '충북', '괴산군');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (109, '충북', '음성군');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (110, '충북', '단양군');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (111, '충남', '천안시');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (112, '충남', '공주시');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (113, '충남', '보령시');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (114, '충남', '아산시');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (115, '충남', '서산시');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (116, '충남', '논산시');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (117, '충남', '계룡시');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (118, '충남', '당진시');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (119, '충남', '금산군');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (120, '충남', '부여군');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (121, '충남', '서천군');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (122, '충남', '청양군');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (123, '충남', '홍성군');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (124, '충남', '예산군');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (125, '충남', '태안군');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (126, '전북', '전주시');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (127, '전북', '군산시');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (128, '전북', '익산시');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (129, '전북', '정읍시');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (130, '전북', '남원시');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (131, '전북', '김제시');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (132, '전북', '완주군');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (133, '전북', '진안군');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (134, '전북', '무주군');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (135, '전북', '장수군');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (136, '전북', '임실군');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (137, '전북', '순창군');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (138, '전북', '고창군');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (139, '전북', '부안군');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (140, '전남', '목포시');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (141, '전남', '여수시');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (142, '전남', '순천시');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (143, '전남', '나주시');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (144, '전남', '광양시');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (145, '전남', '담양군');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (146, '전남', '곡성군');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (147, '전남', '구례군');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (148, '전남', '고흥군');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (149, '전남', '보성군');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (150, '전남', '화순군');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (151, '전남', '장흥군');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (152, '전남', '강진군');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (153, '전남', '해남군');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (154, '전남', '영암군');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (155, '전남', '무안군');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (156, '전남', '함평군');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (157, '전남', '영광군');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (158, '전남', '장성군');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (159, '전남', '완도군');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (160, '전남', '진도군');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (161, '전남', '신안군');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (162, '경북', '포항시');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (163, '경북', '경주시');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (164, '경북', '김천시');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (165, '경북', '안동시');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (166, '경북', '구미시');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (167, '경북', '영주시');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (168, '경북', '영천시');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (169, '경북', '상주시');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (170, '경북', '문경시');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (171, '경북', '경산시');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (172, '경북', '군위군');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (173, '경북', '의성군');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (174, '경북', '청송군');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (175, '경북', '영양군');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (176, '경북', '영덕군');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (177, '경북', '청도군');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (178, '경북', '고령군');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (179, '경북', '성주군');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (180, '경북', '칠곡군');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (181, '경북', '예천군');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (182, '경북', '봉화군');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (183, '경북', '울진군');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (184, '경북', '울릉군');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (185, '경남', '창원시');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (186, '경남', '진주시');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (187, '경남', '통영시');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (188, '경남', '사천시');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (189, '경남', '김해시');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (190, '경남', '밀양시');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (191, '경남', '거제시');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (192, '경남', '양산시');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (193, '경남', '의령군');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (194, '경남', '함안군');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (195, '경남', '창녕군');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (196, '경남', '고성군');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (197, '경남', '남해군');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (198, '경남', '하동군');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (199, '경남', '산청군');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (200, '경남', '함양군');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (201, '경남', '거창군');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (202, '경남', '합천군');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (203, '제주특별자치도', '제주시');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (204, '제주특별자치도', '서귀포시');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (205, '세종특별자치시', '세종시');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (206, '대전', '대덕구');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (207, '대전', '동구');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (208, '대전', '서구');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (209, '대전', '유성구');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (210, '대전', '중구');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (211, '울산', '중구');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (212, '울산', '남구');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (213, '울산', '동구');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (214, '울산', '북구');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (215, '울산', '울주군');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (216, '광주', '서구');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (217, '광주', '남구');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (218, '광주', '동구');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (219, '광주', '북구');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (220, '광주', '광산구');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (221, '인천', '중구');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (222, '인천', '동구');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (223, '인천', '미추홀구');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (224, '인천', '연수구');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (225, '인천', '남동구');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (226, '인천', '부평구');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (227, '인천', '계양구');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (228, '인천', '서구');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (229, '인천', '강화군');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (230, '인천', '옹진군');
-- STORE 매장 ?���?
INSERT INTO STORE (STORE_NO, STORE_NAME, STORE_ADDRESS, STORE_PHONE, BUSINESS_HOURS, STORE_RC, STORE_REGION_NO,
                   STORE_INFO, STATUS)
VALUES (SEQ_STORE.NEXTVAL, '지구샵 제로웨이스트홈', '서울특별시 마포구 성미산로 155 1층, 지구샵', '0507-1372-2052', '11:00 - 21:30', 25, 14,
        '지구를 위한 첫걸음, 지구샵입니다.', 'Y');
INSERT INTO STORE (STORE_NO, STORE_NAME, STORE_ADDRESS, STORE_PHONE, BUSINESS_HOURS, STORE_RC, STORE_REGION_NO,
                   STORE_INFO, STATUS)
VALUES (SEQ_STORE.NEXTVAL, '알맹상점', '서울특별시 마포구 월드컵로25길 47 3층, 알맹상점', '0507-1386-1064', '1112:00 - 20:00', 3, 14, '쓰레기를 줄이는 작은 마음들의 플랫폼
제로 웨이스트 가게이자 리필 스테이션입니다.', 'Y');
INSERT INTO STORE (STORE_NO, STORE_NAME, STORE_ADDRESS, STORE_PHONE, BUSINESS_HOURS, STORE_RC, STORE_REGION_NO,
                   STORE_INFO, STATUS)
VALUES (SEQ_STORE.NEXTVAL, '더피커', '서울특별시 성동구 왕십리로14길 9 1층, 더피커', '070-4118-0710', '12:00 - 20:00', 6, 4,
        '더피커(thepicker)는, 건강한 자연의 소산을 환경에 유해한 포장 없이 순환 가능하도록 세심하게 고르는 사람을 의미합니다.', 'Y');
INSERT INTO STORE (STORE_NO, STORE_NAME, STORE_ADDRESS, STORE_PHONE, BUSINESS_HOURS, STORE_RC, STORE_REGION_NO,
                   STORE_INFO, STATUS)
VALUES (SEQ_STORE.NEXTVAL, '디어얼스', '서울특별시 은평구 녹번로6길 2 1층, 디어얼스', '0507-1300-3388', '12:30 - 19:00', 3, 12,
        '디어얼스는 우리가 일상을 살아가면서 지구를 아끼고 사랑하는 라이프 스타일을 지향합니다.', 'Y');
INSERT INTO STORE (STORE_NO, STORE_NAME, STORE_ADDRESS, STORE_PHONE, BUSINESS_HOURS, STORE_RC, STORE_REGION_NO,
                   STORE_INFO, STATUS)
VALUES (SEQ_STORE.NEXTVAL, '송포어스', '서울특별시 강동구 풍성로35길 3 1층, 송포어스', '0507-1395-3534', '10:30 - 19:00', 12, 25,
        '송포어스는 우리가 일상을 살아가면서 지구를 아끼고 사랑하는 라이프 스타일을 지향합니다.', 'Y');
INSERT INTO STORE (STORE_NO, STORE_NAME, STORE_ADDRESS, STORE_PHONE, BUSINESS_HOURS, STORE_RC, STORE_REGION_NO,
                   STORE_INFO, STATUS)
VALUES (SEQ_STORE.NEXTVAL, '동구밭', '경기 하남시 미사강변서로 25 FB329호, FB330호, FB33', '0507-1306-9626', '10:30 - 19:00', 27, 68,
        '동구밭은 비장애인과 장애인이 함께 지속가능한 일상을 위해 고체 화장품 및 생활용품을 생산하는 브랜드이자 제조사 입니다.', 'Y');
INSERT INTO STORE (STORE_NO, STORE_NAME, STORE_ADDRESS, STORE_PHONE, BUSINESS_HOURS, STORE_RC, STORE_REGION_NO,
                   STORE_INFO, STATUS)
VALUES (SEQ_STORE.NEXTVAL, '소화아람일터', '광주 남구 용대로74번길 27 소화아람일터', '0507-1483-4030', '09:00 - 18:00', 37, 217,
        '자연친화적 제품(비누, 주방세제 등)을 생산, 판매하며 입지 않는 옷을 기증받아 판매하여 중증장애인을 고용합니다.', 'Y');
INSERT INTO STORE (STORE_NO, STORE_NAME, STORE_ADDRESS, STORE_PHONE, BUSINESS_HOURS, STORE_RC, STORE_REGION_NO,
                   STORE_INFO, STATUS)
VALUES (SEQ_STORE.NEXTVAL, '지구별가게', '제주 제주시 월랑로 58 1층', '064-711-8291', '10:00 - 19:00', 102, 203,
        '제로웨이스트 리빙랩, 지구별가게 내 몸과 지구를 살리는 소소한 즐거움, 소락
제로웨이스트를 위한 다회용 생활용품과 유기농 원단으로 직접 제작하는 소락 브랜드 제품을 만나볼 수 있습니다.', 'Y');
INSERT INTO STORE (STORE_NO, STORE_NAME, STORE_ADDRESS, STORE_PHONE, BUSINESS_HOURS, STORE_RC, STORE_REGION_NO,
                   STORE_INFO, STATUS)
VALUES (SEQ_STORE.NEXTVAL, '톤28 라이브러리 성수', '서울특별시 성동구 성수이로12길 2', '0507-1414-0198', '11:30 - 20:30', 58, 4,
        '의식 있는 아름다움, 톤28 라이브러리, 성수입니다.', 'Y');
INSERT INTO STORE (STORE_NO, STORE_NAME, STORE_ADDRESS, STORE_PHONE, BUSINESS_HOURS, STORE_RC, STORE_REGION_NO,
                   STORE_INFO, STATUS)
VALUES (SEQ_STORE.NEXTVAL, '달팽이가게', '전라남도 담양군 수북면 한수동로 548 1층 달팽이가게', '0507-1337-1858', '11:00 - 18:00', 137, 145,
        '제로웨이스트 리필샵& 살림 가게. 나와 아이, 지구에게 더 나은 살림살이. 따뜻한 놀잇감들을 만들고 판매하는 달팽이가게입니다.', 'Y');
INSERT INTO STORE (STORE_NO, STORE_NAME, STORE_ADDRESS, STORE_PHONE, BUSINESS_HOURS, STORE_RC, STORE_REGION_NO,
                   STORE_INFO, STATUS)
VALUES (SEQ_STORE.NEXTVAL, '아이엠그리너', '서울특별시 마포구 잔다리로 44 5층 리와인드', '1522-5710', '10:00 - 16:00', 51, 14,
        '자연에서 얻은 사용소중한 자원을 다시 자연으로 되돌리고자 시작된 소셜벤처로 아이엠그리너 라는 자체 브랜드로 생분해 가능한 일회용품을 제작, 판매 하고 이를 수거하여 테이크아웃 용품의 지속 가능한 순환 플랫폼을 만들어 갑니다.', 'Y');
INSERT INTO STORE (STORE_NO, STORE_NAME, STORE_ADDRESS, STORE_PHONE, BUSINESS_HOURS, STORE_RC, STORE_REGION_NO,
                   STORE_INFO, STATUS)
VALUES (SEQ_STORE.NEXTVAL, '천연제작소 부산점', '부산광역시 북구 덕천1길 93 2층', '051-338-9619', '10:30 - 19:00', 93, 33,
        '환경오염을 줄이는 제품, 세제소분, 부산 최초 제로웨이스트샵', 'Y');
INSERT INTO STORE (STORE_NO, STORE_NAME, STORE_ADDRESS, STORE_PHONE, BUSINESS_HOURS, STORE_RC, STORE_REGION_NO,
                   STORE_INFO, STATUS)
VALUES (SEQ_STORE.NEXTVAL, '임팩토리얼 모레상점', '서울 성동구 뚝섬로1나길 5 헤이그라운드 7층', '070-8633-1333', '09:00 - 19:00', 37, 4,
        '내일 그 다음을 생각하는 지속가능한 책임소비, 모레상점.', 'Y');
INSERT INTO STORE (STORE_NO, STORE_NAME, STORE_ADDRESS, STORE_PHONE, BUSINESS_HOURS, STORE_RC, STORE_REGION_NO,
                   STORE_INFO, STATUS)
VALUES (SEQ_STORE.NEXTVAL, '비누잎', '경기도 군포시 농심로 2 LT삼보 스카이비즈 1412호, 1413호', '0507-1387-0513', '10:00 - 18:00', 62, 66,
        '자연환경과 건강을 생각한 비누를 만듭니다.', 'Y');

-- QNA 더미

INSERT INTO QNA (BOARD_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, MEMBER_ID)
VALUES (1, '아이디를 찾는 법?', '아이디 찾는 법이 어떻게 되나요?', TO_DATE('2023-06-01', 'YYYY-MM-DD'), 'user01');

INSERT INTO QNA (BOARD_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, MEMBER_ID)
VALUES (2, '아이디를 찾는 법?', '아이디 찾는 법이 어떻게 되나요?', TO_DATE('2023-06-02', 'YYYY-MM-DD'), 'user01');

INSERT INTO QNA (BOARD_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, MEMBER_ID)
VALUES (3, '비밀번호를 분실한 경우', '비밀번호를 분실하였습니다. 어떻게 해결할 수 있나요?', TO_DATE('2023-06-03', 'YYYY-MM-DD'), 'user02');

INSERT INTO QNA (BOARD_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, MEMBER_ID)
VALUES (4, '회원가입 문의', '회원가입을 어떻게 진행해야 하나요?', TO_DATE('2023-06-04', 'YYYY-MM-DD'), 'user03');

INSERT INTO QNA (BOARD_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, MEMBER_ID)
VALUES (5, '회원정보 변경', '회원정보 변경은 어떻게 하나요?', TO_DATE('2023-06-05', 'YYYY-MM-DD'), 'user03');

COMMIT;