DROP TABLE STORE;
DROP TABLE STORE_REGION;
DROP TABLE PRODUCT;
DROP TABLE PAYMENT;
DROP TABLE TB_CATEGORY;
DROP TABLE NOTICE;
DROP TABLE QNA;
DROP TABLE MEMBER;
DROP TABLE TB_CODE;
DROP TABLE TB_CHA_FILE;
DROP TABLE MESSAGE;
DROP TABLE TB_CH_DETAIL_INFO;
DROP TABLE LIKES;
DROP TABLE REPORT;
DROP TABLE FAQ;
DROP TABLE STORE_ATTA;
DROP TABLE PRODUCT_ATTA;
DROP TABLE DY_BOARD;
DROP TABLE CHAT;
DROP TABLE GRADE;
DROP TABLE DY_REPLY;
DROP TABLE TB_CH_CON_REPLY;
DROP TABLE REVIEW;
DROP TABLE REVIEW_REPLY;
DROP TABLE ORDERS;
DROP TABLE POINT;
DROP TABLE CART;
DROP TABLE TB_GRP_CODE;
DROP TABLE TB_CATEGORY_TEMPLATE;
DROP TABLE TB_CH_CONFIRM;
DROP TABLE TB_CHALLENGE;

DROP SEQUENCE SEQ_TB_CHALLENGE;
DROP SEQUENCE SEQ_STORE;
DROP SEQUENCE SEQ_PRODUCT;
DROP SEQUENCE SEQ_PAYMENT;
DROP SEQUENCE SEQ_TB_CATEGORY;
DROP SEQUENCE SEQ_NOTICE;
DROP SEQUENCE SEQ_TB_CATEGORY_TEMPLATE;
DROP SEQUENCE SEQ_QNA;
DROP SEQUENCE SEQ_MEMBER;
DROP SEQUENCE SEQ_TB_GRP_CODE;
DROP SEQUENCE SEQ_TB_CODE;
DROP SEQUENCE SEQ_TB_CHA_FILE;
DROP SEQUENCE SEQ_MESSAGE;
DROP SEQUENCE SEQ_TB_CH_CONFIRM;
DROP SEQUENCE SEQ_TB_CH_DETAIL_INFO;
DROP SEQUENCE SEQ_LIKE;
DROP SEQUENCE SEQ_REPORT;
DROP SEQUENCE SEQ_FAQ;
DROP SEQUENCE SEQ_STORE_ATTA;
DROP SEQUENCE SEQ_PRODUCT_ATTA;
DROP SEQUENCE SEQ_DY_BOARD;
DROP SEQUENCE SEQ_CHAT;
DROP SEQUENCE SEQ_GRADE;
DROP SEQUENCE SEQ_DY_REPLY;
DROP SEQUENCE SEQ_TB_CH_CON_REPLY;
DROP SEQUENCE SEQ_REVIEW;
DROP SEQUENCE SEQ_REVIEW_REPLY;
DROP SEQUENCE SEQ_ORDER;
DROP SEQUENCE SEQ_POINT;
DROP SEQUENCE SEQ_CART;


CREATE TABLE TB_CHALLENGE
(
    CH_NO        NUMBER NOT NULL,
    CH_TITLE     VARCHAR2(100) NOT NULL,
    CH_START_DAY VARCHAR2(8) NOT NULL,
    CH_END_DAY   VARCHAR2(8) NOT NULL,
    MEMBER_ID    VARCHAR2(100) NOT NULL,
    CATEGORY_NO  NUMBER NOT NULL,
    FILE_NO      NUMBER NOT NULL,
    CODE         VARCHAR2(8) NOT NULL,
    CH_CONTENT   CLOB NOT NULL
);

CREATE SEQUENCE SEQ_TB_CHALLENGE;

CREATE TABLE STORE_REGION
(
    STORE_REGION_NO NUMBER PRIMARY KEY,
    CITY            VARCHAR2(50),
    PROVINCES       VARCHAR2(50),
    CONSTRAINT city_province_unique UNIQUE (CITY, PROVINCES)
);

CREATE TABLE STORE
(
    STORE_NO        NUMBER           NOT NULL,
    STORE_NAME      VARCHAR2(50) NOT NULL,
    STORE_ADDRESS   VARCHAR2(200) NOT NULL,
    STORE_PHONE     VARCHAR2(30) NULL,
    BUSINESS_HOURS  VARCHAR2(20) NULL,
    STORE_RC        NUMBER DEFAULT 0 NOT NULL,
    STORE_LAT       NUMBER NULL,
    STORE_LON       NUMBER NULL,
    STORE_REGION_NO NUMBER NULL,
    STORE_INFO VARCHAR2(500),
    STATUS CHAR(1) DEFAULT 'Y'     NOT NULL,

    FOREIGN KEY (STORE_REGION_NO) REFERENCES STORE_REGION (STORE_REGION_NO)
);

CREATE SEQUENCE SEQ_STORE;

CREATE TABLE PRODUCT
(
    PRODUCT_NO   NUMBER                  NOT NULL,
    PRODUCT_NAME VARCHAR2(100) NOT NULL,
    CATEGORY     VARCHAR2(20) NOT NULL,
    PRICE        NUMBER                  NOT NULL,
    DISCOUNT     NUMBER  DEFAULT 0       NOT NULL,
    STOCK        NUMBER  DEFAULT 0       NOT NULL,
    CREATE_DATE  DATE    DEFAULT SYSDATE NOT NULL,
    STATUS       CHAR(1) DEFAULT 'Y'     NOT NULL
);

CREATE SEQUENCE SEQ_PRODUCT;

CREATE TABLE PAYMENT
(
    PAYMENT_NO             NUMBER NOT NULL,
    MEMBER_ID              VARCHAR2(100) NOT NULL,
    PAYMENT_DATE           DATE DEFAULT SYSDATE NULL,
    PAYMENT_TYPE           VARCHAR2(20) NOT NULL,
    STATUS                 VARCHAR2(1) NOT NULL,
    PAYMENT_TOTAL          NUMBER NOT NULL,
    RECEIVE_NAME           VARCHAR2(20) NOT NULL,
    RECEIVE_PHONE          VARCHAR2(11) NOT NULL,
    POST_CODE              NUMBER NOT NULL,
    RECEIVE_ADDRESS        VARCHAR2(100) NOT NULL,
    RECEIVE_DETAIL_ADDRESS VARCHAR2(100) NOT NULL
);

CREATE SEQUENCE SEQ_PAYMENT;

CREATE TABLE TB_CATEGORY
(
    CATEGORY_NO   NUMBER NOT NULL,
    CATEGORY_NAME VARCHAR2(100) NOT NULL,
    STATUS        VARCHAR2(1) DEFAULT 'Y' NOT NULL
);

CREATE SEQUENCE SEQ_TB_CATEGORY;

CREATE TABLE NOTICE
(
    NOTICE_NO       NUMBER                  NOT NULL,
    NOTICE_TITLE    VARCHAR2(100) NOT NULL,
    NOTICE_CONTENT  VARCHAR2(500) NOT NULL,
    CREATED_AT      DATE    DEFAULT SYSDATE NOT NULL,
    STATUS          CHAR(1) DEFAULT 'Y'     NOT NULL,
    NOTICE_CATEGORY VARCHAR2(15) NOT NULL,
    NOTICE_VIEW     NUMBER  DEFAULT 0       NOT NULL
);

CREATE SEQUENCE SEQ_NOTICE;

CREATE TABLE TB_CATEGORY_TEMPLATE
(
    CATEGORY_TEMPLATE_NO NUMBER NOT NULL,
    INPUT_TYPE           VARCHAR2(20) NOT NULL,
    STATUS               VARCHAR2(1) DEFAULT 'Y' NOT NULL,
    SORT_NO              NUMBER NOT NULL,
    CH_SUB_TITLE         VARCHAR2(200) NULL,
    GRP_CODE             VARCHAR2(8) NOT NULL,
    CATEGORY_NO          NUMBER NOT NULL
);

CREATE SEQUENCE SEQ_TB_CATEGORY_TEMPLATE;

CREATE TABLE QNA
(
    BOARD_NO      NUMBER               NOT NULL,
    BOARD_TITLE   VARCHAR2(100) NOT NULL,
    BOARD_CONTENT VARCHAR(2000)        NOT NULL,
    BOARD_DATE    DATE DEFAULT SYSDATE NOT NULL,
    BOARD_REPLY   VARCHAR(1000) NULL,
    MEMBER_ID     VARCHAR2(100) NOT NULL
);

CREATE SEQUENCE SEQ_QNA;

CREATE TABLE MEMBER
(
    MEMBER_ID    VARCHAR2(100) NOT NULL,
    MEMBER_PWD   VARCHAR2(100) NOT NULL,
    MEMBER_NAME  VARCHAR2(20) NOT NULL,
    EMAIL        VARCHAR2(30) NOT NULL,
    BIRTH_DATE   DATE NULL,
    PHONE        CHAR(11)                NOT NULL,
    GENDER       CHAR(1) NULL,
    CREATED_DATE DATE    DEFAULT SYSDATE NOT NULL,
    STATUS       CHAR(1) DEFAULT 'Y'     NOT NULL,
    TOTAL_PAY    NUMBER  DEFAULT 0       NOT NULL,
    ADDRESS1     VARCHAR2(255) NULL,
    ADDRESS2     VARCHAR2(255) NULL,
    CHANGE_NAME  VARCHAR2(255) NULL,
    GRADE_NAME   VARCHAR2(15) DEFAULT 'RED' NOT NULL
);

CREATE SEQUENCE SEQ_MEMBER;

CREATE TABLE TB_GRP_CODE
(
    GRP_CODE      VARCHAR2(8) NOT NULL,
    GRP_CODE_NAME VARCHAR2(100) NOT NULL,
    STATUS        VARCHAR2(1) DEFAULT 'Y' NOT NULL
);

CREATE SEQUENCE SEQ_TB_GRP_CODE;

CREATE TABLE TB_CODE
(
    CODE      VARCHAR2(8) NOT NULL,
    GRP_CODE  VARCHAR2(8) NOT NULL,
    CODE_NAME VARCHAR2(100) NOT NULL,
    STATUS    VARCHAR2(1) DEFAULT 'Y' NOT NULL,
    SORT_NO   NUMBER NOT NULL
);

CREATE SEQUENCE SEQ_TB_CODE;

CREATE TABLE TB_CHA_FILE
(
    FILE_NO   NUMBER NOT NULL,
    FILE_NAME VARCHAR2(100) NOT NULL,
    FILE_PATH VARCHAR2(300) NOT NULL
);

CREATE SEQUENCE SEQ_TB_CHA_FILE;

CREATE TABLE MESSAGE
(
    MESSAGE_NO      NUMBER               NOT NULL,
    SEND_TIME       DATE DEFAULT SYSDATE NOT NULL,
    MESSAGE_CONTENT VARCHAR(1000)        NOT NULL,
    CH_NO           NUMBER               NOT NULL,
    CATEGORY_NO     NUMBER               NOT NULL
);

CREATE SEQUENCE SEQ_MESSAGE;

CREATE TABLE TB_CH_CONFIRM
(
    CH_CON_NO          NUMBER               NOT NULL,
    CH_NO              NUMBER               NOT NULL,
    CH_CON_TITLE       VARCHAR2(200) NOT NULL,
    CH_CON_CONTENT     VARCHAR2(4000) NOT NULL,
    MEMBER_ID          VARCHAR2(100) NOT NULL,
    STATUS             VARCHAR2(1) DEFAULT 'Y' NOT NULL,
    CH_CON_CREATE_DATE DATE DEFAULT SYSDATE NOT NULL
);

CREATE SEQUENCE SEQ_TB_CH_CONFIRM;

CREATE TABLE TB_CH_DETAIL_INFO
(
    CH_DETAIL_INFO_NO    NUMBER NOT NULL,
    CH_NO                NUMBER NOT NULL,
    CH_CON_NO            NUMBER NOT NULL,
    CATEGORY_TEMPLATE_NO NUMBER NOT NULL,
    CH_DETAIL_INFO_DATA  VARCHAR2(4000) NOT NULL,
    STATUS               VARCHAR2(1) DEFAULT 'Y' NOT NULL,
    CODE                 VARCHAR2(8) NOT NULL,
    FILE_NO              NUMBER NOT NULL
);

CREATE SEQUENCE SEQ_TB_CH_DETAIL_INFO;

CREATE TABLE LIKES
(
    MEMBER_ID  VARCHAR2(100) NOT NULL,
    PRODUCT_NO NUMBER NOT NULL
);

CREATE SEQUENCE SEQ_LIKE;

CREATE TABLE REPORT
(
    REPORT_NO      NUMBER NOT NULL,
    REPORT_CONTENT VARCHAR2(3000) NOT NULL,
    CH_CON_NO      NUMBER NOT NULL,
    CH_NO          NUMBER NOT NULL,
    DY_BOARD_NO    NUMBER NOT NULL,
    MEMBER_ID      VARCHAR2(100) NOT NULL
);

CREATE SEQUENCE SEQ_REPORT;

CREATE TABLE FAQ
(
    FAQ_NO       NUMBER        NOT NULL,
    FAQ_QUESTION VARCHAR2(100) NOT NULL,
    FAQ_ANSWER   VARCHAR(2000) NOT NULL,
    FAQ_CATEGORY VARCHAR(50)   NOT NULL
);

CREATE SEQUENCE SEQ_FAQ;

CREATE TABLE STORE_ATTA
(
    FILE_NO   NUMBER NOT NULL,
    FILE_NAME VARCHAR2(100) NOT NULL,
    FILE_PATH VARCHAR2(300) NOT NULL,
    STORE_NO  NUMBER NOT NULL
);

CREATE SEQUENCE SEQ_STORE_ATTA;

CREATE TABLE PRODUCT_ATTA
(
    ATTACHMENT_NO NUMBER NOT NULL,
    CHANGER_NAME  VARCHAR2(255) NOT NULL,
    FILE_LEVEL    NUMBER NOT NULL,
    PRODUCT_NO    NUMBER NOT NULL
);

CREATE SEQUENCE SEQ_PRODUCT_ATTA;

CREATE TABLE DY_BOARD
(
    DY_BOARD_NO      NUMBER NOT NULL,
    DY_BOARD_TITLE   VARCHAR2(100) NOT NULL,
    DY_BOARD_CONTENT VARCHAR2(4000) NOT NULL,
    DY_CREATE_DATE   DATE   DEFAULT SYSDATE NULL,
    DY_STATUS        VARCHAR2(1) DEFAULT 'Y' NULL,
    DY_COUNT         NUMBER DEFAULT 0 NULL,
    ORIGIN_NAME      VARCHAR2(100) NOT NULL,
    CHANGE_NAME      VARCHAR2(100) NOT NULL,
    MEMBER_ID        VARCHAR2(100) NOT NULL
);

CREATE SEQUENCE SEQ_DY_BOARD;

CREATE TABLE CHAT
(
    CH_NO       NUMBER NOT NULL,
    CREATE_DATE DATE NULL,
    MEMBER_ID   VARCHAR2(100) NOT NULL
);

CREATE SEQUENCE SEQ_CHAT;

CREATE TABLE GRADE
(
    GRADE_NAME  VARCHAR2(15) DEFAULT 'RED' NOT NULL,
    PAYMENT_MIN NUMBER NOT NULL,
    PAYMENT_MAX NUMBER NOT NULL
);

CREATE SEQUENCE SEQ_GRADE;

CREATE TABLE DY_REPLY
(
    DY_REPLY_NO      NUMBER               NOT NULL,
    DY_BOARD_NO      NUMBER               NOT NULL,
    DY_REPLY_CONTENT VARCHAR2(400) NOT NULL,
    DY_CREATE_DATE   DATE DEFAULT SYSDATE NOT NULL,
    DY_STATUS        VARCHAR2(1) DEFAULT 'Y' NULL,
    MEMBER_ID        VARCHAR2(100) NOT NULL
);

CREATE SEQUENCE SEQ_DY_REPLY;

CREATE TABLE TB_CH_CON_REPLY
(
    RE_NO          NUMBER               NOT NULL,
    CH_CON_NO      NUMBER               NOT NULL,
    CH_NO          NUMBER               NOT NULL,
    RE_CONTENT     VARCHAR2(2000) NOT NULL,
    RE_CREATE_DATE DATE DEFAULT SYSDATE NOT NULL,
    STATUS         VARCHAR2(1) DEFAULT 'Y' NOT NULL,
    MEMBER_ID      VARCHAR2(100) NOT NULL
);

CREATE SEQUENCE SEQ_TB_CH_CON_REPLY;

CREATE TABLE REVIEW
(
    REVIEW_NO      NUMBER               NOT NULL,
    REVIEW_CONTENT VARCHAR2(1000) NOT NULL,
    CREATE_DATE    DATE DEFAULT SYSDATE NOT NULL,
    RATING         NUMBER               NOT NULL,
    CHANGE_NAME    VARCHAR2(255) NULL,
    PRODUCT_NO     NUMBER               NOT NULL,
    MEMBER_ID      VARCHAR2(100) NOT NULL
);

CREATE SEQUENCE SEQ_REVIEW;

CREATE TABLE REVIEW_REPLY
(
    RV_REPLY_NO   NUMBER                  NOT NULL,
    REPLY_CONTENT VARCHAR2(1000) NOT NULL,
    CREATED_DATE  DATE    DEFAULT SYSDATE NOT NULL,
    STATUS        CHAR(1) DEFAULT 'Y'     NOT NULL,
    REVIEW_NO     NUMBER                  NOT NULL,
    MEMBER_ID     VARCHAR2(100) NOT NULL
);

CREATE SEQUENCE SEQ_REVIEW_REPLY;

CREATE TABLE ORDERS
(
    ORDER_NO       NUMBER           NOT NULL,
    PRODUCT_AMOUNT NUMBER DEFAULT 1 NOT NULL,
    PAYMENT_NO     NUMBER           NOT NULL,
    PRODUCT_NO     NUMBER           NOT NULL
);

CREATE SEQUENCE SEQ_ORDER;

CREATE TABLE POINT
(
    POINT_NO      NUMBER               NOT NULL,
    POINT_CONTENT VARCHAR2(300) NOT NULL,
    POINT_NUM     NUMBER               NOT NULL,
    STATUS        CHAR(3)              NOT NULL,
    POINT_DATE    DATE DEFAULT SYSDATE NOT NULL,
    MEMBER_ID     VARCHAR2(100) NOT NULL
);

CREATE SEQUENCE SEQ_POINT;

CREATE TABLE CART
(
    CART_NO    NUMBER NOT NULL,
    AMOUNT     NUMBER NOT NULL,
    PRICE      NUMBER NOT NULL,
    PRODUCT_NO NUMBER NOT NULL,
    MEMBER_ID  VARCHAR2(100) NOT NULL
);

CREATE SEQUENCE SEQ_CART;



ALTER TABLE TB_CHALLENGE
    ADD CONSTRAINT PK_TB_CHALLENGE PRIMARY KEY (CH_NO);

ALTER TABLE STORE
    ADD CONSTRAINT PK_STORE PRIMARY KEY (STORE_NO);

ALTER TABLE PRODUCT
    ADD CONSTRAINT PK_PRODUCT PRIMARY KEY (PRODUCT_NO);

ALTER TABLE PAYMENT
    ADD CONSTRAINT PK_PAYMENT PRIMARY KEY (PAYMENT_NO);

ALTER TABLE TB_CATEGORY
    ADD CONSTRAINT PK_TB_CATEGORY PRIMARY KEY (CATEGORY_NO);

ALTER TABLE NOTICE
    ADD CONSTRAINT PK_NOTICE PRIMARY KEY (NOTICE_NO);

ALTER TABLE TB_CATEGORY_TEMPLATE
    ADD CONSTRAINT PK_TB_CATEGORY_TEMPLATE PRIMARY KEY (CATEGORY_TEMPLATE_NO);

ALTER TABLE QNA
    ADD CONSTRAINT PK_QNA PRIMARY KEY (BOARD_NO);

ALTER TABLE MEMBER
    ADD CONSTRAINT PK_MEMBER PRIMARY KEY (MEMBER_ID);

ALTER TABLE TB_GRP_CODE
    ADD CONSTRAINT PK_TB_GRP_CODE PRIMARY KEY (GRP_CODE);

ALTER TABLE TB_CODE
    ADD CONSTRAINT PK_TB_CODE PRIMARY KEY (CODE, GRP_CODE);

ALTER TABLE TB_CHA_FILE
    ADD CONSTRAINT PK_TB_CHA_FILE PRIMARY KEY (FILE_NO);

ALTER TABLE MESSAGE
    ADD CONSTRAINT PK_MESSAGE PRIMARY KEY (MESSAGE_NO);

ALTER TABLE TB_CH_CONFIRM
    ADD CONSTRAINT PK_TB_CH_CONFIRM PRIMARY KEY (CH_CON_NO, CH_NO);

ALTER TABLE TB_CH_DETAIL_INFO
    ADD CONSTRAINT PK_TB_CH_DETAIL_INFO PRIMARY KEY (CH_DETAIL_INFO_NO, CH_CON_NO, CH_NO, CATEGORY_TEMPLATE_NO);

ALTER TABLE REPORT
    ADD CONSTRAINT PK_REPORT PRIMARY KEY (REPORT_NO);

ALTER TABLE FAQ
    ADD CONSTRAINT PK_FAQ PRIMARY KEY (FAQ_NO);

ALTER TABLE STORE_ATTA
    ADD CONSTRAINT PK_STORE_ATTA PRIMARY KEY (FILE_NO);

ALTER TABLE PRODUCT_ATTA
    ADD CONSTRAINT PK_PRODUCT_ATTA PRIMARY KEY (ATTACHMENT_NO);

ALTER TABLE DY_BOARD
    ADD CONSTRAINT PK_DY_BOARD PRIMARY KEY (DY_BOARD_NO);

ALTER TABLE CHAT
    ADD CONSTRAINT PK_CHAT PRIMARY KEY (CH_NO);

ALTER TABLE GRADE
    ADD CONSTRAINT PK_GRADE PRIMARY KEY (GRADE_NAME);

ALTER TABLE DY_REPLY
    ADD CONSTRAINT PK_DY_REPLY PRIMARY KEY (DY_REPLY_NO);

ALTER TABLE TB_CH_CON_REPLY
    ADD CONSTRAINT PK_TB_CH_CON_REPLY PRIMARY KEY (RE_NO, CH_CON_NO, CH_NO);

ALTER TABLE REVIEW
    ADD CONSTRAINT PK_REVIEW PRIMARY KEY (REVIEW_NO);

ALTER TABLE REVIEW_REPLY
    ADD CONSTRAINT PK_REVIEW_REPLY PRIMARY KEY (RV_REPLY_NO);

ALTER TABLE ORDERS
    ADD CONSTRAINT PK_ORDER PRIMARY KEY (ORDER_NO);

ALTER TABLE POINT
    ADD CONSTRAINT PK_POINT PRIMARY KEY (POINT_NO);

ALTER TABLE CART
    ADD CONSTRAINT PK_CART PRIMARY KEY (CART_NO);



ALTER TABLE TB_CODE
    ADD CONSTRAINT FK_TB_GRP_CODE FOREIGN KEY (GRP_CODE)
        REFERENCES TB_GRP_CODE (GRP_CODE);

ALTER TABLE TB_CH_CONFIRM
    ADD CONSTRAINT FK_TB_CHALLENGE FOREIGN KEY (CH_NO)
        REFERENCES TB_CHALLENGE (CH_NO);

ALTER TABLE TB_CH_DETAIL_INFO
    ADD CONSTRAINT FK_TB_CHALLENGE2 FOREIGN KEY (CH_NO)
        REFERENCES TB_CHALLENGE (CH_NO);

ALTER TABLE TB_CH_DETAIL_INFO
    ADD CONSTRAINT FK_TB_CATEGORY_TEMPLATE FOREIGN KEY (CATEGORY_TEMPLATE_NO)
        REFERENCES TB_CATEGORY_TEMPLATE (CATEGORY_TEMPLATE_NO);

ALTER TABLE CHAT
    ADD CONSTRAINT FK_TB_CHALLENGE3 FOREIGN KEY (CH_NO)
        REFERENCES TB_CHALLENGE (CH_NO);

ALTER TABLE TB_CH_CON_REPLY
    ADD CONSTRAINT FK_TB_CH_CONFIRM1 FOREIGN KEY (CH_CON_NO, CH_NO)
        REFERENCES TB_CH_CONFIRM (CH_CON_NO, CH_NO);


------------------- [ Ï±åÎ¶∞Ïß?Í¥??†® ?ãú?ûë ] ------------------- 
-- < ?†ú?ïΩÏ°∞Í±¥ Î≥?Í≤ΩÏÇ¨?ï≠ >

ALTER TABLE TB_CH_DETAIL_INFO
DROP
CONSTRAINT SYS_C0010294;


ALTER TABLE TB_CH_DETAIL_INFO
DROP
CONSTRAINT SYS_C0010295;


---------------------------------------------------------------------------------------
--  < ?ãú???ä§ Î≥?Í≤ΩÏÇ¨?ï≠ >
-- 1. TB_CATEGORY ?ãú???ä§
DROP SEQUENCE SEQ_CATE_NO;

CREATE SEQUENCE SEQ_CATE_NO
    START WITH 10000000;

SELECT SEQ_CATE_NO.NEXTVAL
FROM DUAL;


-- 2. TB_CATEGORY_TEMPLATE ?ãú???ä§ 
DROP SEQUENCE SEQ_TB_CATEGORY_TEMPLATE;

CREATE SEQUENCE SEQ_TB_CATEGORY_TEMPLATE
    START WITH 10000000;

SELECT SEQ_TB_CATEGORY_TEMPLATE.NEXTVAL
FROM DUAL;


-----------------------------------------------------------------------------------
-- < Ïª¨Îüº Î≥?Í≤ΩÏÇ¨?ï≠ >

ALTER TABLE TB_CHALLENGE DROP COLUMN CODE;

ALTER TABLE TB_CATEGORY_TEMPLATE DROP COLUMN GRP_CODE;

------------------------------------------------------------------------------------
-- < ÏΩîÎ©ò?ä∏ >
-- 1. TB_CATEGORY
COMMENT
ON COLUMN TB_CATEGORY.CATEGORY_NO IS 'Ïπ¥ÌÖåÍ≥†Î¶¨ ?ùº?†®Î≤àÌò∏';
COMMENT
ON COLUMN TB_CATEGORY.CATEGORY_NAME IS 'Ïπ¥ÌÖåÍ≥†Î¶¨Î™?';
COMMENT
ON COLUMN TB_CATEGORY.STATUS IS '?Ç¨?ö©?ó¨Î∂?';

-- 2. TB_CATEGORY_TEMPLATE
COMMENT
ON COLUMN TB_CATEGORY_TEMPLATE.CATEGORY_TEMPLATE_NO IS '?É¨?îåÎ¶? ?ùº?†®Î≤àÌò∏';
COMMENT
ON COLUMN TB_CATEGORY_TEMPLATE.INPUT_TYPE IS '?ûÖ?†•???ûÖ';
COMMENT
ON COLUMN TB_CATEGORY_TEMPLATE.STATUS IS '?Ç¨?ö©?ó¨Î∂?';
COMMENT
ON COLUMN TB_CATEGORY_TEMPLATE.SORT_NO IS '?ö∞?Ñ†?àú?úÑ';
COMMENT
ON COLUMN TB_CATEGORY_TEMPLATE.CH_SUB_TITLE IS 'Ï±åÎ¶∞Ïß? ?Üå?†úÎ™?';
COMMENT
ON COLUMN TB_CATEGORY_TEMPLATE.CATEGORY_NO IS 'Ïπ¥ÌÖåÍ≥†Î¶¨ ?ùº?†®Î≤àÌò∏';

-- 3. TB_CH_CON_REPLY
COMMENT
ON COLUMN TB_CH_CON_REPLY.RE_NO IS '?åìÍ∏?Î≤àÌò∏';
COMMENT
ON COLUMN TB_CH_CON_REPLY.CH_CON_NO IS 'Ï±åÎ¶∞Ïß? ?ù∏Ï¶? ?ùº?†®Î≤àÌò∏';
COMMENT
ON COLUMN TB_CH_CON_REPLY.CH_NO IS 'Ï±åÎ¶∞Ïß? ?ùº?†®Î≤àÌò∏';
COMMENT
ON COLUMN TB_CH_CON_REPLY.RE_CONTENT IS '?åìÍ∏??Ç¥?ö©';
COMMENT
ON COLUMN TB_CH_CON_REPLY.RE_CREATE_DATE IS '?ûë?Ñ±?ùº';
COMMENT
ON COLUMN TB_CH_CON_REPLY.STATUS IS '?Ç¨?ö©?ó¨Î∂?';
COMMENT
ON COLUMN TB_CH_CON_REPLY.MEMBER_ID IS '?öå?õê?ïÑ?ù¥?îî';

-- 4. TB_CH_CONFIRM
COMMENT
ON COLUMN TB_CH_CONFIRM.CH_CON_NO IS 'Ï±åÎ¶∞Ïß? ?ù∏Ï¶? ?ùº?†®Î≤àÌò∏';
COMMENT
ON COLUMN TB_CH_CONFIRM.CH_NO IS 'Ï±åÎ¶∞Ïß? ?ùº?†®Î≤àÌò∏';
COMMENT
ON COLUMN TB_CH_CONFIRM.CH_CON_TITLE IS 'Ï±åÎ¶∞Ïß? ?ù∏Ï¶? ?†úÎ™?';
COMMENT
ON COLUMN TB_CH_CONFIRM.CH_CON_CONTENT IS 'Ï±åÎ¶∞Ïß? ?ù∏Ï¶? ?Ç¥?ö©';
COMMENT
ON COLUMN TB_CH_CONFIRM.MEMBER_ID IS '?öå?õê?ïÑ?ù¥?îî';
COMMENT
ON COLUMN TB_CH_CONFIRM.STATUS IS '?Ç¨?ö©?ó¨Î∂?';
COMMENT
ON COLUMN TB_CH_CONFIRM.CH_CON_CREATE_DATE IS '?ûë?Ñ±?ùº';

-- 5. TB_CH_DETAIL_INFO
COMMENT
ON COLUMN TB_CH_DETAIL_INFO.CH_DETAIL_INFO_NO IS 'Ï±åÎ¶∞Ïß? ?ÉÅ?Ñ∏?†ïÎ≥? ?ùº?†®Î≤àÌò∏';
COMMENT
ON COLUMN TB_CH_DETAIL_INFO.CH_NO IS 'Ï±åÎ¶∞Ïß? ?ùº?†®Î≤àÌò∏';
COMMENT
ON COLUMN TB_CH_DETAIL_INFO.CATEGORY_TEMPLATE_NO IS '?É¨?îåÎ¶? ?ùº?†®Î≤àÌò∏';
COMMENT
ON COLUMN TB_CH_DETAIL_INFO.CH_DETAIL_INFO_DATA IS 'Ï±åÎ¶∞Ïß? ?ÉÅ?Ñ∏?†ïÎ≥? ?ç∞?ù¥?Ñ∞';
COMMENT
ON COLUMN TB_CH_DETAIL_INFO.STATUS IS '?Ç¨?ö©?ó¨Î∂?';
COMMENT
ON COLUMN TB_CH_DETAIL_INFO.CODE IS 'ÏΩîÎìú';
COMMENT
ON COLUMN TB_CH_DETAIL_INFO.FILE_NO IS '?åå?ùº ?ùº?†®Î≤àÌò∏';

-- 6. TB_CHA_FILE
COMMENT
ON COLUMN TB_CHA_FILE.FILE_NO IS '?åå?ùº ?ùº?†®Î≤àÌò∏';
COMMENT
ON COLUMN TB_CHA_FILE.FILE_NAME IS '?åå?ùºÎ™?';
COMMENT
ON COLUMN TB_CHA_FILE.FILE_PATH IS '?åå?ùºÍ≤ΩÎ°ú';

-- 7. TB_CHALLENGE
COMMENT
ON COLUMN TB_CHALLENGE.CH_NO IS 'Ï±åÎ¶∞Ïß? ?ùº?†®Î≤àÌò∏';
COMMENT
ON COLUMN TB_CHALLENGE.CH_TITLE IS 'Ï±åÎ¶∞Ïß?Î™?';
COMMENT
ON COLUMN TB_CHALLENGE.CH_START_DAY IS 'Ï±åÎ¶∞Ïß? ?ãú?ûë?ùº';
COMMENT
ON COLUMN TB_CHALLENGE.CH_END_DAY IS 'Ï±åÎ¶∞Ïß? Ï¢ÖÎ£å?ùº';
COMMENT
ON COLUMN TB_CHALLENGE.MEMBER_ID IS '?öå?õê?ïÑ?ù¥?îî';
COMMENT
ON COLUMN TB_CHALLENGE.CATEGORY_NO IS 'Ïπ¥ÌÖåÍ≥†Î¶¨ ?ùº?†®Î≤àÌò∏';
COMMENT
ON COLUMN TB_CHALLENGE.FILE_NO IS '?åå?ùº ?ùº?†®Î≤àÌò∏';

-- 8. TB_CODE
COMMENT
ON COLUMN TB_CODE.CODE IS 'ÏΩîÎìú';
COMMENT
ON COLUMN TB_CODE.GRP_CODE IS 'Í∑∏Î£πÏΩîÎìú';
COMMENT
ON COLUMN TB_CODE.CODE_NAME IS 'ÏΩîÎìúÎ™?';
COMMENT
ON COLUMN TB_CODE.STATUS IS '?Ç¨?ö©?ó¨Î∂?';
COMMENT
ON COLUMN TB_CODE.SORT_NO IS '?ö∞?Ñ†?àú?úÑ';


-- 9. TB_GRP_CODE
COMMENT
ON COLUMN TB_GRP_CODE.GRP_CODE IS 'Í∑∏Î£πÏΩîÎìú';
COMMENT
ON COLUMN TB_GRP_CODE.GRP_CODE_NAME IS 'Í∑∏Î£πÏΩîÎìúÎ™?';
COMMENT
ON COLUMN TB_GRP_CODE.STATUS IS '?Ç¨?ö©?ó¨Î∂?';
------------------- [ Ï±åÎ¶∞Ïß?Í¥??†® ?Åù ] ------------------- 


-- STORE_REGION ?çîÎØ?
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (1, '?Ñú?ö∏?äπÎ≥ÑÏãú', 'Ï¢ÖÎ°úÍµ?');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (2, '?Ñú?ö∏?äπÎ≥ÑÏãú', 'Ï§ëÍµ¨');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (3, '?Ñú?ö∏?äπÎ≥ÑÏãú', '?ö©?Ç∞Íµ?');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (4, '?Ñú?ö∏?äπÎ≥ÑÏãú', '?Ñ±?èôÍµ?');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (5, '?Ñú?ö∏?äπÎ≥ÑÏãú', 'Í¥ëÏßÑÍµ?');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (6, '?Ñú?ö∏?äπÎ≥ÑÏãú', '?èô??Î¨∏Íµ¨');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (7, '?Ñú?ö∏?äπÎ≥ÑÏãú', 'Ï§ëÎûëÍµ?');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (8, '?Ñú?ö∏?äπÎ≥ÑÏãú', '?Ñ±Î∂ÅÍµ¨');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (9, '?Ñú?ö∏?äπÎ≥ÑÏãú', 'Í∞ïÎ∂ÅÍµ?');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (10, '?Ñú?ö∏?äπÎ≥ÑÏãú', '?èÑÎ¥âÍµ¨');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (11, '?Ñú?ö∏?äπÎ≥ÑÏãú', '?Ö∏?õêÍµ?');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (12, '?Ñú?ö∏?äπÎ≥ÑÏãú', '???èâÍµ?');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (13, '?Ñú?ö∏?äπÎ≥ÑÏãú', '?Ñú??Î¨∏Íµ¨');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (14, '?Ñú?ö∏?äπÎ≥ÑÏãú', 'ÎßàÌè¨Íµ?');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (15, '?Ñú?ö∏?äπÎ≥ÑÏãú', '?ñëÏ≤úÍµ¨');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (16, '?Ñú?ö∏?äπÎ≥ÑÏãú', 'Í∞ïÏÑúÍµ?');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (17, '?Ñú?ö∏?äπÎ≥ÑÏãú', 'Íµ¨Î°úÍµ?');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (18, '?Ñú?ö∏?äπÎ≥ÑÏãú', 'Í∏àÏ≤úÍµ?');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (19, '?Ñú?ö∏?äπÎ≥ÑÏãú', '?òÅ?ì±?è¨Íµ?');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (20, '?Ñú?ö∏?äπÎ≥ÑÏãú', '?èô?ûëÍµ?');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (21, '?Ñú?ö∏?äπÎ≥ÑÏãú', 'Í¥??ïÖÍµ?');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (22, '?Ñú?ö∏?äπÎ≥ÑÏãú', '?ÑúÏ¥àÍµ¨');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (23, '?Ñú?ö∏?äπÎ≥ÑÏãú', 'Í∞ïÎÇ®Íµ?');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (24, '?Ñú?ö∏?äπÎ≥ÑÏãú', '?Ü°?ååÍµ?');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (25, '?Ñú?ö∏?äπÎ≥ÑÏãú', 'Í∞ïÎèôÍµ?');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (26, 'Î∂??Ç∞Í¥ëÏó≠?ãú', 'Ï§ëÍµ¨');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (27, 'Î∂??Ç∞Í¥ëÏó≠?ãú', '?ÑúÍµ?');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (28, 'Î∂??Ç∞Í¥ëÏó≠?ãú', '?èôÍµ?');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (29, 'Î∂??Ç∞Í¥ëÏó≠?ãú', '?òÅ?èÑÍµ?');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (30, 'Î∂??Ç∞Í¥ëÏó≠?ãú', 'Î∂??Ç∞ÏßÑÍµ¨');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (31, 'Î∂??Ç∞Í¥ëÏó≠?ãú', '?èô?ûòÍµ?');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (32, 'Î∂??Ç∞Í¥ëÏó≠?ãú', '?Ç®Íµ?');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (33, 'Î∂??Ç∞Í¥ëÏó≠?ãú', 'Î∂ÅÍµ¨');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (34, 'Î∂??Ç∞Í¥ëÏó≠?ãú', 'Í∞ïÏÑúÍµ?');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (35, 'Î∂??Ç∞Í¥ëÏó≠?ãú', '?ï¥?ö¥??Íµ?');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (36, 'Î∂??Ç∞Í¥ëÏó≠?ãú', '?Ç¨?ïòÍµ?');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (37, 'Î∂??Ç∞Í¥ëÏó≠?ãú', 'Í∏àÏ†ïÍµ?');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (38, 'Î∂??Ç∞Í¥ëÏó≠?ãú', '?ó∞?†úÍµ?');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (39, 'Î∂??Ç∞Í¥ëÏó≠?ãú', '?àò?òÅÍµ?');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (40, 'Î∂??Ç∞Í¥ëÏó≠?ãú', '?Ç¨?ÉÅÍµ?');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (41, 'Î∂??Ç∞Í¥ëÏó≠?ãú', 'Í∏∞Ïû•Íµ?');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (42, '??Íµ¨Í¥ë?ó≠?ãú', 'Ï§ëÍµ¨');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (43, '??Íµ¨Í¥ë?ó≠?ãú', '?èôÍµ?');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (44, '??Íµ¨Í¥ë?ó≠?ãú', '?ÑúÍµ?');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (45, '??Íµ¨Í¥ë?ó≠?ãú', '?Ç®Íµ?');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (46, '??Íµ¨Í¥ë?ó≠?ãú', 'Î∂ÅÍµ¨');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (47, '??Íµ¨Í¥ë?ó≠?ãú', '?àò?Ñ±Íµ?');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (48, '??Íµ¨Í¥ë?ó≠?ãú', '?ã¨?ÑúÍµ?');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (49, '??Íµ¨Í¥ë?ó≠?ãú', '?ã¨?Ñ±Íµ?');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (50, '??Íµ¨Í¥ë?ó≠?ãú', 'Íµ∞ÏúÑÍµ?');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (51, 'Í≤ΩÍ∏∞?èÑ', '?àò?õê?ãú');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (52, 'Í≤ΩÍ∏∞?èÑ', '?Ñ±?Ç®?ãú');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (53, 'Í≤ΩÍ∏∞?èÑ', '?ùò?†ïÎ∂??ãú');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (54, 'Í≤ΩÍ∏∞?èÑ', '?ïà?ñë?ãú');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (55, 'Í≤ΩÍ∏∞?èÑ', 'Î∂?Ï≤úÏãú');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (56, 'Í≤ΩÍ∏∞?èÑ', 'Í¥ëÎ™Ö?ãú');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (57, 'Í≤ΩÍ∏∞?èÑ', '?èâ?Éù?ãú');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (58, 'Í≤ΩÍ∏∞?èÑ', '?èô?ëêÏ≤úÏãú');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (59, 'Í≤ΩÍ∏∞?èÑ', '?ïà?Ç∞?ãú');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (60, 'Í≤ΩÍ∏∞?èÑ', 'Í≥†Ïñë?ãú');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (61, 'Í≤ΩÍ∏∞?èÑ', 'Í≥ºÏ≤ú?ãú');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (62, 'Í≤ΩÍ∏∞?èÑ', 'Íµ¨Î¶¨?ãú');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (63, 'Í≤ΩÍ∏∞?èÑ', '?Ç®?ñëÏ£ºÏãú');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (64, 'Í≤ΩÍ∏∞?èÑ', '?ò§?Ç∞?ãú');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (65, 'Í≤ΩÍ∏∞?èÑ', '?ãú?ù•?ãú');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (66, 'Í≤ΩÍ∏∞?èÑ', 'Íµ∞Ìè¨?ãú');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (67, 'Í≤ΩÍ∏∞?èÑ', '?ùò?ôï?ãú');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (68, 'Í≤ΩÍ∏∞?èÑ', '?ïò?Ç®?ãú');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (69, 'Í≤ΩÍ∏∞?èÑ', '?ö©?ù∏?ãú');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (70, 'Í≤ΩÍ∏∞?èÑ', '?ååÏ£ºÏãú');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (71, 'Í≤ΩÍ∏∞?èÑ', '?ù¥Ï≤úÏãú');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (72, 'Í≤ΩÍ∏∞?èÑ', '?ïà?Ñ±?ãú');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (73, 'Í≤ΩÍ∏∞?èÑ', 'Íπ??è¨?ãú');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (74, 'Í≤ΩÍ∏∞?èÑ', '?ôî?Ñ±?ãú');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (75, 'Í≤ΩÍ∏∞?èÑ', 'Í¥ëÏ£º?ãú');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (76, 'Í≤ΩÍ∏∞?èÑ', '?ñëÏ£ºÏãú');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (77, 'Í≤ΩÍ∏∞?èÑ', '?è¨Ï≤úÏãú');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (78, 'Í≤ΩÍ∏∞?èÑ', '?ó¨Ï£ºÏãú');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (79, 'Í≤ΩÍ∏∞?èÑ', '?ó∞Ï≤úÍµ∞');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (80, 'Í≤ΩÍ∏∞?èÑ', 'Í∞??èâÍµ?');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (81, 'Í≤ΩÍ∏∞?èÑ', '?ñë?èâÍµ?');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (82, 'Í∞ïÏõê?èÑ', 'Ï∂òÏ≤ú?ãú');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (83, 'Í∞ïÏõê?èÑ', '?õêÏ£ºÏãú');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (84, 'Í∞ïÏõê?èÑ', 'Í∞ïÎ¶â?ãú');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (85, 'Í∞ïÏõê?èÑ', '?èô?ï¥?ãú');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (86, 'Í∞ïÏõê?èÑ', '?ÉúÎ∞±Ïãú');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (87, 'Í∞ïÏõê?èÑ', '?ÜçÏ¥àÏãú');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (88, 'Í∞ïÏõê?èÑ', '?ÇºÏ≤ôÏãú');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (89, 'Í∞ïÏõê?èÑ', '?ôçÏ≤úÍµ∞');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (90, 'Í∞ïÏõê?èÑ', '?ö°?Ñ±Íµ?');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (91, 'Í∞ïÏõê?èÑ', '?òÅ?õîÍµ?');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (92, 'Í∞ïÏõê?èÑ', '?èâÏ∞ΩÍµ∞');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (93, 'Í∞ïÏõê?èÑ', '?†ï?Ñ†Íµ?');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (94, 'Í∞ïÏõê?èÑ', 'Ï≤†ÏõêÍµ?');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (95, 'Í∞ïÏõê?èÑ', '?ôîÏ≤úÍµ∞');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (96, 'Í∞ïÏõê?èÑ', '?ñëÍµ¨Íµ∞');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (97, 'Í∞ïÏõê?èÑ', '?ù∏?†úÍµ?');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (98, 'Í∞ïÏõê?èÑ', 'Í≥†ÏÑ±Íµ?');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (99, 'Í∞ïÏõê?èÑ', '?ñë?ñëÍµ?');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (100, 'Ï∂©Ï≤≠Î∂ÅÎèÑ', 'Ï≤?Ï£ºÏãú');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (101, 'Ï∂©Ï≤≠Î∂ÅÎèÑ', 'Ï∂©Ï£º?ãú');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (102, 'Ï∂©Ï≤≠Î∂ÅÎèÑ', '?†úÏ≤úÏãú');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (103, 'Ï∂©Ï≤≠Î∂ÅÎèÑ', 'Î≥¥Ï?Íµ?');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (104, 'Ï∂©Ï≤≠Î∂ÅÎèÑ', '?ò•Ï≤úÍµ∞');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (105, 'Ï∂©Ï≤≠Î∂ÅÎèÑ', '?òÅ?èôÍµ?');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (106, 'Ï∂©Ï≤≠Î∂ÅÎèÑ', 'Ï¶ùÌèâÍµ?');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (107, 'Ï∂©Ï≤≠Î∂ÅÎèÑ', 'ÏßÑÏ≤úÍµ?');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (108, 'Ï∂©Ï≤≠Î∂ÅÎèÑ', 'Í¥¥ÏÇ∞Íµ?');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (109, 'Ï∂©Ï≤≠Î∂ÅÎèÑ', '?ùå?Ñ±Íµ?');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (110, 'Ï∂©Ï≤≠Î∂ÅÎèÑ', '?ã®?ñëÍµ?');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (111, 'Ï∂©Ï≤≠?Ç®?èÑ', 'Ï≤úÏïà?ãú');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (112, 'Ï∂©Ï≤≠?Ç®?èÑ', 'Í≥µÏ£º?ãú');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (113, 'Ï∂©Ï≤≠?Ç®?èÑ', 'Î≥¥Î†π?ãú');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (114, 'Ï∂©Ï≤≠?Ç®?èÑ', '?ïÑ?Ç∞?ãú');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (115, 'Ï∂©Ï≤≠?Ç®?èÑ', '?Ñú?Ç∞?ãú');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (116, 'Ï∂©Ï≤≠?Ç®?èÑ', '?Öº?Ç∞?ãú');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (117, 'Ï∂©Ï≤≠?Ç®?èÑ', 'Í≥ÑÎ£°?ãú');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (118, 'Ï∂©Ï≤≠?Ç®?èÑ', '?ãπÏßÑÏãú');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (119, 'Ï∂©Ï≤≠?Ç®?èÑ', 'Í∏àÏÇ∞Íµ?');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (120, 'Ï∂©Ï≤≠?Ç®?èÑ', 'Î∂??ó¨Íµ?');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (121, 'Ï∂©Ï≤≠?Ç®?èÑ', '?ÑúÏ≤úÍµ∞');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (122, 'Ï∂©Ï≤≠?Ç®?èÑ', 'Ï≤??ñëÍµ?');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (123, 'Ï∂©Ï≤≠?Ç®?èÑ', '?ôç?Ñ±Íµ?');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (124, 'Ï∂©Ï≤≠?Ç®?èÑ', '?òà?Ç∞Íµ?');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (125, 'Ï∂©Ï≤≠?Ç®?èÑ', '?Éú?ïàÍµ?');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (126, '?†Ñ?ùºÎ∂ÅÎèÑ', '?†ÑÏ£ºÏãú');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (127, '?†Ñ?ùºÎ∂ÅÎèÑ', 'Íµ∞ÏÇ∞?ãú');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (128, '?†Ñ?ùºÎ∂ÅÎèÑ', '?ùµ?Ç∞?ãú');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (129, '?†Ñ?ùºÎ∂ÅÎèÑ', '?†ï?ùç?ãú');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (130, '?†Ñ?ùºÎ∂ÅÎèÑ', '?Ç®?õê?ãú');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (131, '?†Ñ?ùºÎ∂ÅÎèÑ', 'Íπ??†ú?ãú');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (132, '?†Ñ?ùºÎ∂ÅÎèÑ', '?ôÑÏ£ºÍµ∞');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (133, '?†Ñ?ùºÎ∂ÅÎèÑ', 'ÏßÑÏïàÍµ?');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (134, '?†Ñ?ùºÎ∂ÅÎèÑ', 'Î¨¥Ï£ºÍµ?');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (135, '?†Ñ?ùºÎ∂ÅÎèÑ', '?û•?àòÍµ?');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (136, '?†Ñ?ùºÎ∂ÅÎèÑ', '?ûÑ?ã§Íµ?');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (137, '?†Ñ?ùºÎ∂ÅÎèÑ', '?àúÏ∞ΩÍµ∞');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (138, '?†Ñ?ùºÎ∂ÅÎèÑ', 'Í≥†Ï∞ΩÍµ?');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (139, '?†Ñ?ùºÎ∂ÅÎèÑ', 'Î∂??ïàÍµ?');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (140, '?†Ñ?ùº?Ç®?èÑ', 'Î™©Ìè¨?ãú');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (141, '?†Ñ?ùº?Ç®?èÑ', '?ó¨?àò?ãú');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (142, '?†Ñ?ùº?Ç®?èÑ', '?àúÏ≤úÏãú');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (143, '?†Ñ?ùº?Ç®?èÑ', '?ÇòÏ£ºÏãú');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (144, '?†Ñ?ùº?Ç®?èÑ', 'Í¥ëÏñë?ãú');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (145, '?†Ñ?ùº?Ç®?èÑ', '?ã¥?ñëÍµ?');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (146, '?†Ñ?ùº?Ç®?èÑ', 'Í≥°ÏÑ±Íµ?');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (147, '?†Ñ?ùº?Ç®?èÑ', 'Íµ¨Î?Íµ?');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (148, '?†Ñ?ùº?Ç®?èÑ', 'Í≥†Ìù•Íµ?');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (149, '?†Ñ?ùº?Ç®?èÑ', 'Î≥¥ÏÑ±Íµ?');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (150, '?†Ñ?ùº?Ç®?èÑ', '?ôî?àúÍµ?');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (151, '?†Ñ?ùº?Ç®?èÑ', '?û•?ù•Íµ?');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (152, '?†Ñ?ùº?Ç®?èÑ', 'Í∞ïÏßÑÍµ?');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (153, '?†Ñ?ùº?Ç®?èÑ', '?ï¥?Ç®Íµ?');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (154, '?†Ñ?ùº?Ç®?èÑ', '?òÅ?ïîÍµ?');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (155, '?†Ñ?ùº?Ç®?èÑ', 'Î¨¥ÏïàÍµ?');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (156, '?†Ñ?ùº?Ç®?èÑ', '?ï®?èâÍµ?');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (157, '?†Ñ?ùº?Ç®?èÑ', '?òÅÍ¥ëÍµ∞');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (158, '?†Ñ?ùº?Ç®?èÑ', '?û•?Ñ±Íµ?');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (159, '?†Ñ?ùº?Ç®?èÑ', '?ôÑ?èÑÍµ?');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (160, '?†Ñ?ùº?Ç®?èÑ', 'ÏßÑÎèÑÍµ?');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (161, '?†Ñ?ùº?Ç®?èÑ', '?ã†?ïàÍµ?');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (162, 'Í≤ΩÏÉÅÎ∂ÅÎèÑ', '?è¨?ï≠?ãú');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (163, 'Í≤ΩÏÉÅÎ∂ÅÎèÑ', 'Í≤ΩÏ£º?ãú');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (164, 'Í≤ΩÏÉÅÎ∂ÅÎèÑ', 'Íπ?Ï≤úÏãú');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (165, 'Í≤ΩÏÉÅÎ∂ÅÎèÑ', '?ïà?èô?ãú');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (166, 'Í≤ΩÏÉÅÎ∂ÅÎèÑ', 'Íµ¨Î?∏Ïãú');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (167, 'Í≤ΩÏÉÅÎ∂ÅÎèÑ', '?òÅÏ£ºÏãú');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (168, 'Í≤ΩÏÉÅÎ∂ÅÎèÑ', '?òÅÏ≤úÏãú');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (169, 'Í≤ΩÏÉÅÎ∂ÅÎèÑ', '?ÉÅÏ£ºÏãú');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (170, 'Í≤ΩÏÉÅÎ∂ÅÎèÑ', 'Î¨∏Í≤Ω?ãú');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (171, 'Í≤ΩÏÉÅÎ∂ÅÎèÑ', 'Í≤ΩÏÇ∞?ãú');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (172, 'Í≤ΩÏÉÅÎ∂ÅÎèÑ', 'Íµ∞ÏúÑÍµ?');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (173, 'Í≤ΩÏÉÅÎ∂ÅÎèÑ', '?ùò?Ñ±Íµ?');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (174, 'Í≤ΩÏÉÅÎ∂ÅÎèÑ', 'Ï≤??Ü°Íµ?');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (175, 'Í≤ΩÏÉÅÎ∂ÅÎèÑ', '?òÅ?ñëÍµ?');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (176, 'Í≤ΩÏÉÅÎ∂ÅÎèÑ', '?òÅ?çïÍµ?');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (177, 'Í≤ΩÏÉÅÎ∂ÅÎèÑ', 'Ï≤??èÑÍµ?');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (178, 'Í≤ΩÏÉÅÎ∂ÅÎèÑ', 'Í≥†Î†πÍµ?');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (179, 'Í≤ΩÏÉÅÎ∂ÅÎèÑ', '?Ñ±Ï£ºÍµ∞');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (180, 'Í≤ΩÏÉÅÎ∂ÅÎèÑ', 'Ïπ†Í≥°Íµ?');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (181, 'Í≤ΩÏÉÅÎ∂ÅÎèÑ', '?òàÏ≤úÍµ∞');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (182, 'Í≤ΩÏÉÅÎ∂ÅÎèÑ', 'Î¥âÌôîÍµ?');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (183, 'Í≤ΩÏÉÅÎ∂ÅÎèÑ', '?ö∏ÏßÑÍµ∞');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (184, 'Í≤ΩÏÉÅÎ∂ÅÎèÑ', '?ö∏Î¶âÍµ∞');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (185, 'Í≤ΩÏÉÅ?Ç®?èÑ', 'Ï∞ΩÏõê?ãú');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (186, 'Í≤ΩÏÉÅ?Ç®?èÑ', 'ÏßÑÏ£º?ãú');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (187, 'Í≤ΩÏÉÅ?Ç®?èÑ', '?Üµ?òÅ?ãú');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (188, 'Í≤ΩÏÉÅ?Ç®?èÑ', '?Ç¨Ï≤úÏãú');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (189, 'Í≤ΩÏÉÅ?Ç®?èÑ', 'Íπ??ï¥?ãú');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (190, 'Í≤ΩÏÉÅ?Ç®?èÑ', 'Î∞??ñë?ãú');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (191, 'Í≤ΩÏÉÅ?Ç®?èÑ', 'Í±∞Ï†ú?ãú');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (192, 'Í≤ΩÏÉÅ?Ç®?èÑ', '?ñë?Ç∞?ãú');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (193, 'Í≤ΩÏÉÅ?Ç®?èÑ', '?ùò?†πÍµ?');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (194, 'Í≤ΩÏÉÅ?Ç®?èÑ', '?ï®?ïàÍµ?');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (195, 'Í≤ΩÏÉÅ?Ç®?èÑ', 'Ï∞ΩÎÖïÍµ?');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (196, 'Í≤ΩÏÉÅ?Ç®?èÑ', 'Í≥†ÏÑ±Íµ?');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (197, 'Í≤ΩÏÉÅ?Ç®?èÑ', '?Ç®?ï¥Íµ?');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (198, 'Í≤ΩÏÉÅ?Ç®?èÑ', '?ïò?èôÍµ?');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (199, 'Í≤ΩÏÉÅ?Ç®?èÑ', '?Ç∞Ï≤?Íµ?');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (200, 'Í≤ΩÏÉÅ?Ç®?èÑ', '?ï®?ñëÍµ?');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (201, 'Í≤ΩÏÉÅ?Ç®?èÑ', 'Í±∞Ï∞ΩÍµ?');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (202, 'Í≤ΩÏÉÅ?Ç®?èÑ', '?ï©Ï≤úÍµ∞');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (203, '?†úÏ£ºÌäπÎ≥ÑÏûêÏπòÎèÑ', '?†úÏ£ºÏãú');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (204, '?†úÏ£ºÌäπÎ≥ÑÏûêÏπòÎèÑ', '?ÑúÍ∑??è¨?ãú');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (205, '?Ñ∏Ï¢ÖÌäπÎ≥ÑÏûêÏπòÏãú', '?Ñ∏Ï¢ÖÏãú');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (206, '???†ÑÍ¥ëÏó≠?ãú', '???çïÍµ?');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (207, '???†ÑÍ¥ëÏó≠?ãú', '?èôÍµ?');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (208, '???†ÑÍ¥ëÏó≠?ãú', '?ÑúÍµ?');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (209, '???†ÑÍ¥ëÏó≠?ãú', '?ú†?Ñ±Íµ?');
INSERT INTO STORE_REGION (STORE_REGION_NO, CITY, PROVINCES)
VALUES (210, '???†ÑÍ¥ëÏó≠?ãú', 'Ï§ëÍµ¨');

-- STORE Îß§Ïû• ?çîÎØ?
INSERT INTO STORE (STORE_NO, STORE_NAME, STORE_ADDRESS, STORE_PHONE, BUSINESS_HOURS, STORE_RC, STORE_REGION_NO,
                   STORE_INFO)
VALUES (SEQ_STORE.NEXTVAL, 'Ïß?Íµ¨ÏÉµ ?†úÎ°úÏõ®?ù¥?ä§?ä∏?ôà', '?Ñú?ö∏ ÎßàÌè¨Íµ? ?Ñ±ÎØ∏ÏÇ∞Î°? 155 1Ï∏?, Ïß?Íµ¨ÏÉµ', '0507-1372-2052', '11:00 - 21:30', 25, 14,
        'Ïß?Íµ¨Î?? ?úÑ?ïú Ï≤´Í±∏?ùå, Ïß?Íµ¨ÏÉµ?ûÖ?ãà?ã§.');
INSERT INTO STORE (STORE_NO, STORE_NAME, STORE_ADDRESS, STORE_PHONE, BUSINESS_HOURS, STORE_RC, STORE_REGION_NO,
                   STORE_INFO)
VALUES (SEQ_STORE.NEXTVAL, '?ïåÎßπÏÉÅ?†ê', '?Ñú?ö∏ ÎßàÌè¨Íµ? ?õî?ìúÏªµÎ°ú25Í∏? 47 3Ï∏?, ?ïåÎßπÏÉÅ?†ê', '0507-1386-1064', '1112:00 - 20:00', 3, 14, '"?ì∞?†àÍ∏∞Î?? Ï§ÑÏù¥?äî ?ûë?? ÎßàÏùå?ì§?ùò ?îå?û´?èº
?†úÎ°? ?õ®?ù¥?ä§?ä∏ Í∞?Í≤åÏù¥?ûê Î¶¨ÌïÑ ?ä§?Öå?ù¥?Öò?ûÖ?ãà?ã§."');
INSERT INTO STORE (STORE_NO, STORE_NAME, STORE_ADDRESS, STORE_PHONE, BUSINESS_HOURS, STORE_RC, STORE_REGION_NO,
                   STORE_INFO)
VALUES (SEQ_STORE.NEXTVAL, '?çî?îºÏª?', '?Ñú?ö∏ ?Ñ±?èôÍµ? ?ôï?ã≠Î¶¨w2?çî?îºÏª?', '070-4118-0710', '12:00 - 20:00', 6, 4,
        '?çî?îºÏª?(thepicker)?äî, Í±¥Í∞ï?ïú ?ûê?ó∞?ùò ?Üå?Ç∞?ùÑ ?ôòÍ≤ΩÏóê ?ú†?ï¥?ïú ?è¨?û• ?óÜ?ù¥ ?àú?ôò Í∞??ä•?ïò?èÑÎ°? ?Ñ∏?ã¨?ïòÍ≤? Í≥†Î•¥?äî ?Ç¨?ûå?ùÑ ?ùòÎØ∏Ìï©?ãà?ã§.');
INSERT INTO STORE (STORE_NO, STORE_NAME, STORE_ADDRESS, STORE_PHONE, BUSINESS_HOURS, STORE_RC, STORE_REGION_NO,
                   STORE_INFO)
VALUES (SEQ_STORE.NEXTVAL, '?îî?ñ¥?ñº?ä§', '?Ñú?ö∏ ???èâÍµ? ?ÖπÎ≤àÎ°ú6Í∏? 21 1Ï∏?, ?îî?ñ¥?ñº?ä§', '0507-1300-3388', '12:30 - 19:00', 3, 12,
        '?îî?ñ¥?ñº?ä§?äî ?ö∞Î¶¨Í? ?ùº?ÉÅ?ùÑ ?Ç¥?ïÑÍ∞?Î©¥ÏÑú Ïß?Íµ¨Î?? ?ïÑ?ÅºÍ≥? ?Ç¨?ûë?ïò?äî ?ùº?ù¥?îÑ ?ä§???ùº?ùÑ Ïß??ñ•?ï©?ãà?ã§.');
INSERT INTO STORE (STORE_NO, STORE_NAME, STORE_ADDRESS, STORE_PHONE, BUSINESS_HOURS, STORE_RC, STORE_REGION_NO,
                   STORE_INFO)
VALUES (SEQ_STORE.NEXTVAL, '?Ü°?è¨?ñ¥', '?Ñú?ö∏ Í∞ïÎèôÍµ? ?íç?Ñ±Î°?35Í∏? 34 1Ï∏?, ?Ü°?è¨?ñ¥?ä§', '0507-1395-3534', '10:30 - 19:00', 12, 25,
        '?Ü°?è¨?ñ¥?ä§?äî ?ö∞Î¶¨Í? ?ùº?ÉÅ?ùÑ ?Ç¥?ïÑÍ∞?Î©¥ÏÑú Ïß?Íµ¨Î?? ?ïÑ?ÅºÍ≥? ?Ç¨?ûë?ïò?äî ?ùº?ù¥?îÑ ?ä§???ùº?ùÑ Ïß??ñ•?ï©?ãà?ã§.');
